// SPDX-FileCopyrightText: Copyright 2014 Basis Technology Corp.
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Autopsy Forensic Browser
 *
 * Copyright 2014 Basis Technology Corp.
 * Contact: carrier <at> sleuthkit <dot> org *

 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;

/**
 * Ingest job settings for the keywords search module.
 */
public final class Main {

    private static long serialVersionUID = 1L;
    private static boolean DEFAULT_INDEX_TO_SOLR = true;
    
    private HashSet<String> namesOfEnabledKeywordLists = null;
    private HashSet<String> namesOfDisabledKeywordLists = null; // Added in version 1.1

    /**
     * These are nullable so that if no serialized setting, the setting can
     * defer to legacy KeywordSearchSettings.
     */
    private Boolean ocrEnabled = null;
    private Boolean limitedOCREnabled = null;

    private boolean ocrOnly = Verifier.nondetBoolean();
    
    // use object boolean so older settings missing this setting will deserialize to null.
    private Boolean indexToSolr = null;

    /**
     * Constructs ingest job settings for the keywords search module.
     *
     * @param namesOfEnabledKeywordLists A list of enabled keywords lists.
     */
    /** ARG-V: suitable */
	 Main(List<String> namesOfEnabledKeywordLists) {
        this.namesOfEnabledKeywordLists = new HashSet<>(namesOfEnabledKeywordLists);
        this.namesOfDisabledKeywordLists = new HashSet<>();
        
        // explicitly set to default value
        this.ocrEnabled = null;
        this.limitedOCREnabled = null;
        this.ocrOnly = false;
        this.indexToSolr = true;
    }

    /**
     * Constructs ingest job settings for the keywords search module.
     *
     * @param namesOfEnabledKeywordLists  A list of enabled keywords lists.
     * @param namesOfDisabledKeywordLists A list of disabled keywords lists.
     * @param ocrEnabled                  Whether or not OCR is enabled for
     *                                    keyword search.
     * @param limitedOCREnabled           If true, OCR is to be performed only
     *                                    on images larger than 100KB.
     * @param ocrOnly                     True if keyword search ingest should
     *                                    be solely limited to OCR.
     */
    /** ARG-V: suitable */
	 Main(List<String> namesOfEnabledKeywordLists, List<String> namesOfDisabledKeywordLists, boolean ocrEnabled, boolean limitedOCREnabled, boolean ocrOnly, boolean indexToSolr) {
        this.namesOfEnabledKeywordLists = new HashSet<>(namesOfEnabledKeywordLists);
        this.namesOfDisabledKeywordLists = new HashSet<>(namesOfDisabledKeywordLists);
        this.ocrEnabled = ocrEnabled;
        this.limitedOCREnabled = limitedOCREnabled;
        this.ocrOnly = ocrOnly;
        this.indexToSolr = indexToSolr;
    }


    /**
     * Checks whether or not a keywords list is enabled. If there is no setting
     * for the requested list, it is deemed to be enabled.
     *
     * @param keywordListName The name of the keywords list to check.
     *
     * @return True if the keywords list is enabled, false otherwise.
     */
    /** ARG-V: suitable */
	 boolean keywordListIsEnabled(String keywordListName) {
        this.upgradeFromOlderVersions();
        assert namesOfEnabledKeywordLists != null; //inline assert generated by ARG-V
		return namesOfEnabledKeywordLists.contains(keywordListName);
    }

    /**
     * Get the names of all explicitly enabled keywords lists.
     *
     * @return The list of names.
     */
    /** ARG-V: suitable */
	 List<String> getNamesOfEnabledKeyWordLists() {
        this.upgradeFromOlderVersions();
		return new ArrayList<>(namesOfEnabledKeywordLists);
    }

    /**
     * Get the names of all explicitly disabled keywords lists.
     *
     * @return The list of names.
     */
    /** ARG-V: suitable */
	 List<String> getNamesOfDisabledKeyWordLists() {
        this.upgradeFromOlderVersions();
		return new ArrayList<>(namesOfDisabledKeywordLists);
    }

    /**
     * Initialize fields set to null when an instance of a previous, but still
     * compatible, version of this class is de-serialized.
     */
    /** ARG-V: suitable */
	 private void upgradeFromOlderVersions() {
        if (null == this.namesOfDisabledKeywordLists) {
            this.namesOfDisabledKeywordLists = new HashSet<>();
        }
        assert this.namesOfDisabledKeywordLists != null;
    }
    
    /** ARG-V: suitable */
	 boolean isIndexToSolrEnabled() {
        assert true; //inline assert generated by ARG-V
		return indexToSolr == null ? DEFAULT_INDEX_TO_SOLR : indexToSolr;
    }
	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        String keyword1 = Verifier.nondetString();
        String keyword2 = Verifier.nondetString();
        String keyword3 = Verifier.nondetString();
        String keyword4 = Verifier.nondetString();
        List<String> namesOfEnabledKeywordLists = new ArrayList<>();
        namesOfEnabledKeywordLists.add(keyword1);
        namesOfEnabledKeywordLists.add(keyword2);
        namesOfEnabledKeywordLists.add(keyword3);
        namesOfEnabledKeywordLists.add(keyword4);
        List<String> namesOfDisabledKeywordLists = new ArrayList<>();
        namesOfDisabledKeywordLists.add(keyword1);
        namesOfDisabledKeywordLists.add(keyword2);
        boolean ocrEnabled = Verifier.nondetBoolean();
        boolean limitedOCREnabled = Verifier.nondetBoolean();
        boolean ocrOnly = Verifier.nondetBoolean();
        boolean indexToSolr = true;
        Main instance=new Main(namesOfEnabledKeywordLists,namesOfDisabledKeywordLists,ocrEnabled,limitedOCREnabled,ocrOnly,indexToSolr);

        assert instance.keywordListIsEnabled(keyword1);
        assert instance.isIndexToSolrEnabled();
        List<String> copy_namesOfEnabledKeywordLists = instance.getNamesOfEnabledKeyWordLists();
        List<String> copy_namesOfDisabledKeywordLists = instance.getNamesOfDisabledKeyWordLists();
        assert copy_namesOfEnabledKeywordLists.size() <= namesOfEnabledKeywordLists.size();
        assert copy_namesOfDisabledKeywordLists.size() <= namesOfDisabledKeywordLists.size();
    }

}
