// SPDX-License-Identifier: MulanPSL-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreePath;

public class Main {

	private JTree tree = null;

	/** ARG-V: suitable */
	 public Main() {
	}

	/** ARG-V: suitable */
	 public Main(JTree tree) {
		this.tree = tree;
	}

	/** ARG-V: suitable */
	 public Set<String> getExpansionState() {
		Set<String> openedSet = new HashSet<>();
		if (tree != null) {
			int rowCount = tree.getRowCount();
			for (int i = 0; i < rowCount; i++) {
				TreePath path = tree.getPathForRow(i);
				if (tree.isExpanded(path)) {
					String rowPathStr = getRowPathStr(path);
					// for switching Package Explorer on/off
					openedSet.addAll(getAllParentPathsStr(rowPathStr));
				}
			}
		}
		assert openedSet != null;
		assert openedSet.size() <= tree.getRowCount();
		return openedSet;
	}

	/** ARG-V: suitable */
	 private Set<String> getAllParentPathsStr(String rowPathStr) {
		Set<String> parents = new HashSet<>();
		parents.add(rowPathStr);
		if (rowPathStr.contains("/")) {
			String[] pathElements = rowPathStr.split("/");
			String path = "";
		}
		assert parents.size() == 1;
		return parents;
	}

	/** ARG-V: suitable */
	 public void restoreExpanstionState(Set<String> expansionState) {
		if (tree != null && expansionState != null) {
			// tree.getRowCount() changes at tree.expandRow()
			for (int i = 0; i < tree.getRowCount(); i++) {
				TreePath path = tree.getPathForRow(i);
				if (expansionState.contains(getRowPathStr(path))) {
					tree.expandRow(i);
				}
			}
		}
	}

	/** ARG-V: suitable */
	 private String getRowPathStr(TreePath trp) {
		String pathStr = "";
		if (trp.getPathCount() > 1) {
			for (int i = 1; i < trp.getPathCount(); i++) {
				DefaultMutableTreeNode node = (DefaultMutableTreeNode) trp.getPathComponent(i);
				pathStr = Verifier.nondetString();
			}
		}
		assert trp.getPathCount() == 1; // could be 2
		return pathStr;
	}

	/** ARG-V: suitable */
	 public JTree getTree() {
		assert tree != null; //inline assert generated by ARG-V
		return tree;
	}

	/** ARG-V: suitable */
	 public void setTree(JTree tree) {
		this.tree = tree;
	}

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
		DefaultMutableTreeNode root = new DefaultMutableTreeNode("root");
		DefaultMutableTreeNode node = new DefaultMutableTreeNode("node");
		root.add(node);
		JTree tree = new JTree(root);
		Main instance = new Main(tree);
		Set<String> expansionState = instance.getExpansionState();
		instance.restoreExpanstionState(expansionState);
		
		JTree instanceTree = instance.getTree();
		assert instanceTree != null;
	}
}
