// SPDX-FileCopyrightText: Copyright (C) Blazebit
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.AnnotationValue;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.Parameterizable;
import javax.lang.model.element.TypeElement;
import javax.lang.model.element.TypeParameterElement;
import javax.lang.model.element.VariableElement;
import javax.lang.model.type.DeclaredType;
import javax.lang.model.type.ExecutableType;
import javax.lang.model.type.TypeKind;
import javax.lang.model.type.TypeMirror;
import javax.lang.model.util.Elements;
import javax.lang.model.util.Types;
import javax.tools.Diagnostic;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.ServiceLoader;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

/**
 * @author Christian Beikov
 * @since 1.5.0
 */
public class Main {

    private static Object NULL_OBJECT = new Object();
    private ProcessingEnvironment pe = null;
    private boolean logDebug = Verifier.nondetBoolean();
    private String generatedAnnotation = Verifier.nondetString();

    private Map<CharSequence, Object> typeElements = new HashMap<>();
    private Map<String, TypeMirror> optionalParameters = null;
    private Map<String, Map<String, Element>> initializedViewTypes = new HashMap<>();
    private Map<String, Map<String, Element>> initializedViewFilters = new HashMap<>();
    private Map<String, Map<String, Element>> initializedEntities = new HashMap<>();

    private int threads = Verifier.nondetInt();

    /** ARG-V: suitable */
	 public Main(ProcessingEnvironment pe) {
        this.pe = pe;
        this.logDebug = Verifier.nondetBoolean();

        Map<String, TypeMirror> optionalParameters = new HashMap<>();
        TypeElement java8AndBelowGeneratedAnnotation = pe == null ? null : pe.getElementUtils().getTypeElement("javax.annotation.Generated");
        if (java8AndBelowGeneratedAnnotation != null) {
            generatedAnnotation = java8AndBelowGeneratedAnnotation.getQualifiedName().toString();
        } else {
            // Using the new name for this annotation in Java 9 and above
            generatedAnnotation = "javax.annotation.processing.Generated";
        }
        String threads = Verifier.nondetString();
        if (threads == null || threads.isEmpty()) {
            this.threads = Runtime.getRuntime().availableProcessors();
        } else {
            this.threads = 1;
        }

        this.optionalParameters = optionalParameters;
    }


    /** ARG-V: suitable */
	 public TypeElement getTypeElement(CharSequence name) {
        Object cached = typeElements.get(name);
        if (cached != null) {
            assert false; //inline assert generated by ARG-V
			return null;
        }
        TypeElement typeElement = pe == null ? null : pe.getElementUtils().getTypeElement(name);
        if (typeElement == null) {
            typeElements.put(name, NULL_OBJECT);
        } else {
            typeElements.put(name, typeElement);
        }
        assert typeElements.containsValue(NULL_OBJECT); //inline assert generated by ARG-V
		return typeElement;
    }


    /** ARG-V: suitable */
	 public Map<String, Element> initializeEntityViewElement(TypeElement entityView) {
        String entityViewFqn = entityView == null ? "" : entityView.toString();
        Map<String, Element> members = initializedViewTypes.get(entityViewFqn);
        if (members != null) {
            assert false; //inline assert generated by ARG-V
			return members;
        }


        initializeEnclosingElements(entityView);
        initializedViewTypes.put(entityViewFqn, members);
        assert initializedViewTypes.containsValue(null); //inline assert generated by ARG-V
		return members;
    }

    /** ARG-V: suitable */
	 private void initializeEnclosingElements(TypeElement typeElement) {
        Element enclosingElement = typeElement == null ? null : typeElement.getEnclosingElement();
        while (enclosingElement != null) {
            assert false;
            enclosingElement.getKind();
            enclosingElement = enclosingElement.getEnclosingElement();
        }
    }



    /** ARG-V: suitable */
	 public Object getAllMembers(TypeElement typeElement) {
        String fqn = typeElement == null ? "" : typeElement.toString();
        Map<String, Element> elements = initializedViewTypes.get(fqn);
        if (elements != null) {
            assert false; //inline assert generated by ARG-V
			return new Object();
        }
        elements = initializedEntities.get(fqn);
        if (elements != null) {
            assert false; //inline assert generated by ARG-V
			return new Object();
        }
        elements = initializedViewFilters.get(fqn);
        if (elements != null) {
            assert false; //inline assert generated by ARG-V
			return new Object();
        }
        assert elements == null; //inline assert generated by ARG-V
		return null;
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        // ConcurrentHashMap operations are not null-safe
        Main instance=new Main((javax.annotation.processing.ProcessingEnvironment)null);
        TypeElement te = instance.getTypeElement((java.lang.CharSequence)null);
        assert te == null;
        instance.initializeEntityViewElement(te);
        assert instance.getAllMembers(te) == null;
    }
}
