// SPDX-FileCopyrightText: Copyright (C) Blazebit
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.List;

/**
 * A listener that adds the built entity view to a list.
 *
 * @author Christian Beikov
 * @since 1.5.0
 */
public class Main {

    private List<Object> list = null;
    private int index = Verifier.nondetInt();

    /**
     * Creates the listener.
     *
     * @param list The list to add a built entity view to
     * @param index The index to which to add the entity view to
     */
    /** ARG-V: suitable */
	 public Main(List<Object> list, int index) {
        this.list = list;
        this.index = index;
    }

    /** ARG-V: suitable */
	 public void onBuildComplete(Object object) {
        if (index > list.size()) {
            for (int i = list.size(); i < index; i++) {
                list.add(null);
            }
            list.add(object);
        } else if (index < list.size()) {
            list.set(index, object);
        } else {
            list.add(object);
        }
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        List<Object> list = new java.util.ArrayList<Object>();
        int index = Verifier.nondetInt();
        Main instance=new Main(list, index);
        Object object = new Object();
        instance.onBuildComplete(object);
        assert list.get(index - 1).equals(object);
    }
}
