// SPDX-FileCopyrightText: Copyright (c) 2005, Oracle and/or its affiliates
// SPDX-License-Identifier: GPL-2.0-only WITH Classpath-exception-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright (c) 2005, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.List;
import java.util.ArrayList;

import javax.xml.namespace.QName;
import javax.xml.stream.events.EndElement;
import javax.xml.stream.events.Namespace;

import java.io.PrintWriter;
import java.io.Writer;
import java.util.Iterator;
import javax.xml.stream.events.XMLEvent;

/**
 * Implementation of EndElement event.
 *
 * @author Neeraj Bajaj Sun Microsystems,Inc.
 * @author K.Venugopal Sun Microsystems,Inc.
 */

public class Main {

    public QName fQName = null;

    /** ARG-V: suitable */
    public Main(String prefix, String uri, String localpart) {
        this(new QName(uri, localpart, prefix));
    }

    /** ARG-V: suitable */
    public Main(QName qname) {
        this.fQName = qname;
    }

    /** ARG-V: suitable */
    protected void writeAsEncodedUnicodeEx(java.io.Writer writer) throws Exception {
        writer.write("</");
        String prefix = fQName.getPrefix();
        if (prefix != null && prefix.length() > 0) {
            writer.write(prefix);
            writer.write(':');
        }
        writer.write(fQName.getLocalPart());
        writer.write('>');
    }

    /** ARG-V: suitable */
    public String toString() {
        String s = "</" + nameAsString();
        s = s + ">";
        assert s.matches("</.*>"); // inline assert generated by ARG-V
        return s;
    }

    /** ARG-V: suitable */
    public String nameAsString() {
        if ("".equals(fQName.getNamespaceURI()))
            return Verifier.nondetString();
        if (fQName.getPrefix() != null)
            return Verifier.nondetString();
        else
            return Verifier.nondetString();
    }

    /** This main was generated by ARG-V */

    public static void main(String[] args) throws Exception {
        Main instance = new Main(Verifier.nondetString(), Verifier.nondetString(), Verifier.nondetString());
        Writer writer = new PrintWriter(System.out);
        instance.writeAsEncodedUnicodeEx(writer);
        String s = instance.toString();
        assert s.contains(instance.fQName.getLocalPart());
    }

}
