// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.*;
import java.util.Map;
import java.util.Properties;

/**
 * Reads and stores configuration information for a POS tagger.
 *
 * <i>Implementation note:</i> To add a new parameter: (1) define a
 * default String value, (2) add it to defaultValues map, (3) add line
 * to constructor via setProperties, (4) add getter method, (5) add to
 * dump() method, (6) add to printGenProps() method, (7) add to class
 * javadoc of MaxentTagger.
 *
 * @author William Morgan
 * @author Anna Rafferty
 * @author Michel Galley
 */
public class Main {

  /*
   * defaults. sentenceDelimiter might be null; the others all have non-null
   * values.
   */
  public static String SEARCH = "qn",
      TAG_SEPARATOR = "/",
      TOKENIZE = "true",
      DEBUG = "false",
      ITERATIONS = "100",
      ARCH = "",
      WORD_FUNCTION = "",
      RARE_WORD_THRESH = "5",
      MIN_FEATURE_THRESH = "5",
      CUR_WORD_MIN_FEATURE_THRESH = "2",
      RARE_WORD_MIN_FEATURE_THRESH = "10",
      VERY_COMMON_WORD_THRESH = "250",
      OCCURRING_TAGS_ONLY = "false",
      POSSIBLE_TAGS_ONLY = "false",
      SIGMA_SQUARED = String.valueOf(0.5),
      ENCODING = "UTF-8",
      LEARN_CLOSED_CLASS = "false",
      CLOSED_CLASS_THRESHOLD = "40",
      VERBOSE = "false",
      VERBOSE_RESULTS = "true",
      SGML = "false",
      LANG = "",
      TOKENIZER_FACTORY = "",
      XML_INPUT = "",
      TAG_INSIDE = "",
      APPROXIMATE = "-1.0",
      TOKENIZER_OPTIONS = "",
      DEFAULT_REG_L1 = "1.0",
      OUTPUT_FILE = "",
      OUTPUT_FORMAT = "slashTags",
      OUTPUT_FORMAT_OPTIONS = "",
      NTHREADS = "1",
      MIN_WORDS_LOCK_TAGS = "1";

  public static String ENCODING_PROPERTY = "encoding",
      TAG_SEPARATOR_PROPERTY = "tagSeparator";


  /**
   * This constructor is just for creating an instance with default values.
   * Used internally.
   */
  /** ARG-V: suitable */
  private Main() {
  }

  /** ARG-V: suitable */
  public Main(String... args) {
    this();
  }


  /** ARG-V: suitable */
  public String getFile() {
    return Verifier.nondetString();
  }

  /** ARG-V: suitable */
  public String[] getOutputOptions() {
    return new java.lang.String[] { Verifier.nondetString() };
  }

  /** ARG-V: suitable */
  public boolean getOutputVerbosity() {
    return getOutputOptionsContains("verbose");
  }

  /** ARG-V: suitable */
  public boolean getOutputLemmas() {
    return getOutputOptionsContains("lemmatize");
  }

  /** ARG-V: suitable */
  public boolean keepEmptySentences() {
    return getOutputOptionsContains("keepEmptySentences");
  }

  /** ARG-V: suitable */
  public boolean getOutputOptionsContains(String sought) {
    String[] options = getOutputOptions();
    assert options.length == 1; // inline assert generated by ARG-V
    return options[0].contains(sought);
  }


  /** ARG-V: suitable */
  public String getLang() {
    return Verifier.nondetString();
  }

  /** ARG-V: suitable */
  public boolean getTokenize() {
    return Boolean.parseBoolean(Verifier.nondetString());
  }

  /** ARG-V: suitable */
  public String getTokenizerOptions() {
    return Verifier.nondetString();
  }

  /** ARG-V: suitable */
  public boolean getTokenizerInvertible() {
    String tokenizerOptions = getTokenizerOptions();
    if (tokenizerOptions != null && tokenizerOptions.matches("(^|.*,)invertible=true")){
      return true;
    }
    assert  !tokenizerOptions.startsWith("invertible=true") && !tokenizerOptions.endsWith(",invertible=true"); // inline assert generated by ARG-V
    return getOutputVerbosity() || getOutputLemmas();
  }

  /**
   * Returns a default score to be used for each tag that is incompatible with
   * the current word (e.g., the tag CC for the word "apple"). Using a default
   * score may slightly decrease performance for some languages (e.g., Chinese and
   * German), but allows the tagger to run considerably faster (since the
   * computation
   * of the normalization term Z requires much less feature extraction). This
   * approximation
   * does not decrease performance in English (on the WSJ). If this function
   * returns
   * 0.0, the tagger will compute exact scores.
   *
   * @return default score
   */
  /** ARG-V: suitable */
  public double getDefaultScore() {
    String approx = Verifier.nondetString();
    if (approx == null) {
      assert false; // inline assert generated by ARG-V
      return getLang().equals("english") ? 1.0 : 0.0;
    } else if ("false".equalsIgnoreCase(approx)) {
      assert approx.toUpperCase().equals("FALSE"); // inline assert generated by ARG-V
      return -1.0;
    } else if ("true".equalsIgnoreCase(approx)) {
      assert approx.toLowerCase().equals("true"); // inline assert generated by ARG-V
      return 1.0;
    } else {
      if (approx.matches("-?\\d+(\\.\\d+)?")){
        return 1.5;
        // return Double.parseDouble(approx);
      }
      return 0.0;
    }
  }

  /** ARG-V: suitable */
  public void dump() {
    dump(new PrintWriter(System.err));
  }

  /** ARG-V: suitable */
  public void dump(PrintStream stream) {
    PrintWriter pw = new PrintWriter(stream);
    dump(pw);
  }

  /** ARG-V: suitable */
  private void dump(PrintWriter pw) {
    pw.println("            " + TAG_SEPARATOR_PROPERTY + " = ");
    pw.println("                " + ENCODING_PROPERTY + " = ");
    pw.flush();
  }


  /**
   * This returns the sentence delimiter used when tokenizing text
   * using the tokenizer requested in this config. In general, it is
   * assumed the tokenizer doesn't need a sentence delimiter.... If you
   * use the whitespace tokenizer, though, a newline breaks sentences.
   *
   * @return A null String unless tokenize is false and then the String
   */
  /** ARG-V: suitable */
  public String getSentenceDelimiter() {
    String delimiter = Verifier.nondetString();
    if (delimiter == null && !getTokenize()) {
      delimiter = "\n";
    }
    assert delimiter != null; // inline assert generated by ARG-V
    return delimiter;
  }

  /**
   * Returns whether or not we should use stdin for reading when
   * tagging data. For now, this returns true iff the filename given
   * was "stdin".
   * (TODO: kind of ugly)
   */
  /** ARG-V: suitable */
  public boolean useStdin() {
    return getFile().trim().equalsIgnoreCase("stdin");
  }

  /**
   * Prints out the automatically generated props file - in its own
   * method to make code above easier to read
   */
  /** ARG-V: suitable */
  public static void printGenProps(PrintStream out) {
    out.println("## Sample properties file for maxent tagger. This file is used for three main");
    out.println("## operations: training, testing, and tagging. It may also be used to dump");
    out.println("## the contents of a model.");
    out.println("## To train or test a model, or to tag something, run:");
    out.println("##   java edu.stanford.nlp.tagger.maxent.MaxentTagger -prop <properties file>");
    out.println("## Arguments can be overridden on the commandline, e.g.:");
    out.println("##   java ....MaxentTagger -prop <properties file> -testFile /other/file ");
    out.println();

    out.println("# Model file name (created at train time; used at tag and test time)");
    out.println("# (you can leave this blank and specify it on the commandline with -model)");
    out.println("# model = ");
    out.println();

    out.println("# Path to file to be operated on (trained from, tested against, or tagged)");
    out.println("# Specify -textFile <filename> to tag text in the given file, -trainFile <filename> to");
    out.println("# to train a model using data in the given file, or -testFile <filename> to test your");
    out.println("# model using data in the given file.  Alternatively, you may specify");
    out.println("# -dump <filename> to dump the parameters stored in a model or ");
    out.println("# -convertToSingleFile <filename> to save an old, multi-file model (specified as -model)");
    out.println("# to the new single file format.  The new model will be saved in the file filename.");
    out.println("# If you choose to convert an old file, you must specify ");
    out.println("# the correct 'arch' parameter used to create the original model.");
    out.println("# trainFile = ");
    out.println();

    out.println("# Path to outputFile to write tagged output to.");
    out.println("# If empty, stdout is used.");
    out.println("# outputFile = " + OUTPUT_FILE);
    out.println();

    out.println("# Output format. One of: slashTags (default), xml, or tsv");
    out.println("# outputFormat = " + OUTPUT_FORMAT);
    out.println();

    out.println("# Output format options. Comma separated list.");
    out.println("# currently \"lemmatize\" and \"keepEmptySentences\" are supported.");
    out.println("# outputFormatOptions = " + OUTPUT_FORMAT_OPTIONS);
    out.println();

    out.println("# Tag separator character that separates word and pos tags");
    out.println("# (for both training and test data) and used for");
    out.println("# separating words and tags in slashTags format output.");
    out.println("# tagSeparator = " + TAG_SEPARATOR);
    out.println();

    out.println("# Encoding format in which files are stored.  If left blank, UTF-8 is assumed.");
    out.println("# encoding = " + ENCODING);
    out.println();

    out.println("# A couple flags for controlling the amount of output:");
    out.println("# - print extra debugging information:");
    out.println("# verbose = " + VERBOSE);
    out.println("# - print intermediate results:");
    out.println("# verboseResults = " + VERBOSE_RESULTS);

    out.println("######### parameters for tag and test operations #########");
    out.println();

    out.println("# Class to use for tokenization. Default blank value means Penn Treebank");
    out.println("# tokenization.  If you'd like to just assume that tokenization has been done,");
    out.println("# and the input is whitespace-tokenized, use");
    out.println("# edu.stanford.nlp.process.WhitespaceTokenizer or set tokenize to false.");
    out.println("# tokenizerFactory = ");
    out.println();

    out.println("# Options to the tokenizer.  A comma separated list.");
    out.println("# This depends on what the tokenizer supports.");
    out.println("# For PTBTokenizer, you might try options like americanize=false");
    out.println("# or quotes=ascii (for German!).");
    out.println("# tokenizerOptions = ");
    out.println();
    out.println("# Whether to tokenize text for tag and test operations. Default is true.");
    out.println("# If false, your text must already be whitespace tokenized.");
    out.println("# tokenize = " + TOKENIZE);
    out.println();

    out.println("# Write debugging information (words, top words, unknown words). Useful for");
    out.println("# error analysis. Default is false.");
    out.println("# debug = " + DEBUG);
    out.println();

    out.println("# Prefix for debugging output (if debug == true). Default is to use the");
    out.println("# filename from 'file'");
    out.println("# debugPrefix = ");
    out.println();

    out.println("######### parameters for training  #########");
    out.println();

    out.println("# model architecture: This is one or more comma separated strings, which");
    out.println("# specify which extractors to use. Some of them take one or more integer");
    out.println("# or string ");
    out.println("# (file path) arguments in parentheses, written as m, n, and s below:");
    out.println("# 'left3words', 'left5words', 'bidirectional', 'bidirectional5words',");
    out.println("# 'generic', 'sighan2005', 'german', 'words(m,n)', 'wordshapes(m,n)',");
    out.println("# 'biwords(m,n)', 'lowercasewords(m,n)', 'vbn(n)', distsimconjunction(s,m,n)',");
    out.println("# 'naacl2003unknowns', 'naacl2003conjunctions', 'distsim(s,m,n)',");
    out.println("# 'suffix(n)', 'prefix(n)', 'prefixsuffix(n)', 'capitalizationsuffix(n)',");
    out.println("# 'wordshapes(m,n)', 'unicodeshapes(m,n)', 'unicodeshapeconjunction(m,n)',");
    out.println("# 'lctagfeatures', 'order(k)', 'chinesedictionaryfeatures(s)'.");
    out.println("# These keywords determines the features extracted.  'generic' is language independent.");
    out.println("# distsim: Distributional similarity classes can be an added source of information");
    out.println("# about your words. An English distsim file is included, or you can use your own.");
    out.println("# arch = ");
    out.println();
    out.println("# 'wordFunction'.  A function applied to the text before training or tagging.");
    out.println("# For example, edu.stanford.nlp.util.LowercaseFunction");
    out.println("# This function turns all the words into lowercase");
    out.println("# The function must implement java.util.function.Function<String, String>");
    out.println("# Blank means no preprocessing function");
    out.println("# wordFunction = ");
    out.println();

    out.println("# 'language'.  This is really the tag set which is used for the");
    out.println("# list of open-class tags, and perhaps deterministic  tag");
    out.println("# expansion). Currently we have 'english', 'arabic', 'german', 'chinese'");
    out.println("# or 'polish' predefined. For your own language, you can specify ");
    out.println("# the same information via openClassTags or closedClassTags below");
    out.println("# (only ONE of these three options may be specified). ");
    out.println("# 'english' means UPenn English treebank tags. 'german' is STTS");
    out.println("# 'chinese' is CTB, and Arabic is an expanded Bies mapping from the ATB");
    out.println("# 'polish' means some tags that some guy on the internet once used. ");
    out.println("# See the TTags class for more information.");
    out.println("# lang = ");
    out.println();

    out.println("# a space-delimited list of open-class parts of speech");
    out.println(
        "# alternatively, you can specify language above to use a pre-defined list or specify the closed class tags (below)");
    out.println("# openClassTags = ");
    out.println();

    out.println("# a space-delimited list of closed-class parts of speech");
    out.println(
        "# alternatively, you can specify language above to use a pre-defined list or specify the open class tags (above)");
    out.println("# closedClassTags = ");
    out.println();

    out.println("# A boolean indicating whether you would like the trained model to set POS tags as closed");
    out.println(
        "# based on their frequency in training; default is false.  The frequency threshold can be set below. ");
    out.println("# This option is ignored if any of {openClassTags, closedClassTags, lang} are specified.");
    out.println("# learnClosedClassTags = ");
    out.println();

    out.println("# Used only if learnClosedClassTags=true.  Tags that have fewer tokens than this threshold are");
    out.println("# considered closed in the trained model.");
    out.println("# closedClassTagThreshold = ");
    out.println();

    out.println("# search method for optimization. Normally use the default 'qn'. choices: 'qn' (quasi-Newton),");
    out.println("# 'cg' (conjugate gradient, 'owlqn' (L1 regularization) or 'iis' (improved iterative scaling)");
    out.println("# search = " + SEARCH);
    out.println();

    out.println("# for conjugate gradient or quasi-Newton search, sigma-squared smoothing/regularization");
    out.println("# parameter. if left blank, the default is 0.5, which is usually okay");
    out.println("# sigmaSquared = " + SIGMA_SQUARED);
    out.println();

    out.println("# for OWLQN search, regularization");
    out.println("# parameter. if left blank, the default is 1.0, which is usually okay");
    out.println("# regL1 = " + DEFAULT_REG_L1);
    out.println();

    out.println("# For improved iterative scaling, the number of iterations, otherwise ignored");
    out.println("# iterations = " + ITERATIONS);
    out.println();

    out.println("# rare word threshold. words that occur less than this number of");
    out.println("# times are considered rare words.");
    out.println("# rareWordThresh = " + RARE_WORD_THRESH);
    out.println();

    out.println("# minimum feature threshold. features whose history appears less");
    out.println("# than this number of times are ignored.");
    out.println("# minFeatureThresh = " + MIN_FEATURE_THRESH);
    out.println();

    out.println("# current word feature threshold. words that occur more than this");
    out.println("# number of times will generate features with all of their occurring");
    out.println("# tags.");
    out.println("# curWordMinFeatureThresh = " + CUR_WORD_MIN_FEATURE_THRESH);
    out.println();

    out.println("# rare word minimum feature threshold. features of rare words whose histories");
    out.println("# appear less than this times will be ignored.");
    out.println("# rareWordMinFeatureThresh = " + RARE_WORD_MIN_FEATURE_THRESH);
    out.println();

    out.println("# very common word threshold. words that occur more than this number of");
    out.println("# times will form an equivalence class by themselves. ignored unless");
    out.println("# you are using equivalence classes.");
    out.println("# veryCommonWordThresh = " + VERY_COMMON_WORD_THRESH);
    out.println();

    out.println("# sgml = ");
    out.println("# tagInside = ");
    out.println();

    out.println("# testFile and textFile can use multiple threads to process text.");
    out.println("# nthreads = " + NTHREADS);
    out.println();

    out.println("# The tagger will only use tags it has seen for a particular word");
    out.println("# if the word occurred at least this many times in the training data.");
    out.println("# minWordsLockTags = " + MIN_WORDS_LOCK_TAGS);
  }



  /** This main was generated by ARG-V */

  public static void main(String[] args) throws Exception {
    Main instance = new Main();
    boolean keepEmptySentences = instance.keepEmptySentences();
    boolean tokenizerInvertible = keepEmptySentences && instance.getTokenizerInvertible();
    double defaultScore = instance.getDefaultScore();
    instance.getSentenceDelimiter();
    PrintStream out = instance.useStdin() ? System.out: System.err;
    instance.dump();
    printGenProps(out);
    assert tokenizerInvertible || (defaultScore < 2.0 && defaultScore > -2.0);
  }

}
