// SPDX-FileCopyrightText: Copyright (C) 2016-2023 ActionTech
// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016-2023 ActionTech.
 * License: http://www.gnu.org/licenses/gpl.html GPL version 2 or higher.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.sql.SQLException;
import java.sql.SQLNonTransientException;
import java.util.*;

/**
 * lock tables [table] [writeDirectly|read]
 *
 * @author songdabin
 */
public class Main {
    /** ARG-V: suitable */
	 public void addTableToSet(Map<String, Set<String>> tableSet, String schema, String table) {
        if (tableSet.get(schema) == null) {
            Set<String> set = new HashSet<>();
            set.add(schema);
            tableSet.put(schema, set);
        } else {
            tableSet.get(schema).add(table);
        }
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        Main instance=new Main();
        Map<String, Set<String>> tableSet = new HashMap<>();
        String schema = Verifier.nondetString();
        String table = Verifier.nondetString();
        instance.addTableToSet(tableSet, schema, table);
        assert tableSet.get(schema).contains(table);
    }
}
