// SPDX-FileCopyrightText: Copyright (C) 2013-2025 The Apache Software Foundation
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Main {
  /**
   * If storage plugin has several workspaces, picks appropriate one and removes the others.
   */
  /** ARG-V: suitable */
 private void transformWorkspaces(List<String> names, Map configMap) {
    Object workspaces = configMap.remove("workspaces");
    if (workspaces != null) {
      Map map = (Map) workspaces;
      String key = "workspace";
      Object workspace = map.get(key);
      if (workspace != null) {
        Map workspaceMap = (Map) map.get(key);
        configMap.putAll(workspaceMap);
      } else if (Verifier.nondetBoolean()) {
        configMap.putAll(null);
      }
    }
  }

/** This main was generated by ARG-V */
 public static void main(String[] args) throws Exception{
    Main instance=new Main();
    Map configMap = new HashMap();
    Map workspaces = new HashMap();
    Map workspace = new HashMap();
    String key = Verifier.nondetString();
    String value = Verifier.nondetString();

    workspace.put(key, value);
    workspaces.put("workspace", workspace);
    configMap.put("workspaces", workspaces);

    instance.transformWorkspaces((java.util.List<java.lang.String>)null,configMap);
    assert configMap.containsKey(key);
    assert configMap.get(key).equals(key);
  }
}
