// SPDX-FileCopyrightText: Copyright 2011-2017 Basis Technology Corp.
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Autopsy Forensic Browser
 *
 * Copyright 2011-2017 Basis Technology Corp.
 * Contact: carrier <at> sleuthkit <dot> org
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.beans.PropertyChangeListener;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.logging.Level;
import javax.swing.plaf.basic.BasicRootPaneUI;

/**
 * Provides thread-safe support for publishing events to registered subscribers
 * on this Autopsy node. Subscribers are constrained to be
 * PropertyChangeListeners to integrate with the legacy use of JavaBeans
 * PropertyChangeEvents and PropertyChangeListeners as an application event
 * system.
 */
final class Main {

    public Map<String, Set<PropertyChangeListener>> subscribersByEvent = null;

    /**
     * Constructs an object for publishing events to registered subscribers on
     * this Autopsy node.
     */
    /** ARG-V: suitable */
	 Main() {
        subscribersByEvent = new ConcurrentHashMap<>();
    }

    /**
     * Adds an event subscriber to this publisher.
     *
     * @param eventName  The event the subscriber is interested in.
     * @param subscriber The subscriber to add.
     */
    /** ARG-V: suitable */
	 void addSubscriber(String eventName, PropertyChangeListener subscriber) {
        subscribersByEvent.putIfAbsent(eventName, ConcurrentHashMap.<PropertyChangeListener>newKeySet());
        Set<PropertyChangeListener> subscribers = subscribersByEvent.get(eventName);
        subscribers.add(subscriber);
    }

    /**
     * Removes an event subscriber from this publisher.
     *
     * @param eventNames The event the subscriber is no longer interested in.
     * @param subscriber The subscriber to remove.
     */
    /** ARG-V: suitable */
	 void removeSubscriber(String eventName, PropertyChangeListener subscriber) {
        Set<PropertyChangeListener> subscribers = subscribersByEvent.getOrDefault(eventName, null);
        if (null != subscribers) {
            subscribers.remove(subscriber);
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
        PropertyChangeListener subscriber = new BasicRootPaneUI();
        String eventName = Verifier.nondetString();
		instance.addSubscriber(eventName, subscriber);
        Set<PropertyChangeListener> subscribers = instance.subscribersByEvent.getOrDefault(eventName, null);
        assert subscribers != null;
        assert subscribers.contains(subscriber);
		instance.removeSubscriber(eventName, subscriber);
        assert subscribers.contains(subscriber);
	}

}
