// SPDX-FileCopyrightText: Copyright (c) 2023 LinkedIn Corp.
// SPDX-License-Identifier: BSD-2-Clause
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright 2023 LinkedIn Corp. Licensed under the BSD 2-Clause License (the "License"). See License in the project root for license information.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * The summary of the currency execution concurrency. It provides the current
 * min/max/avg value of the broker concurrency of different type.
 */
public class Main {
  private Map<Integer, Integer> _interBrokerPartitionMovementConcurrency = null;
  private Map<Integer, Integer> _intraBrokerPartitionMovementConcurrency = null;
  private Map<Integer, Integer> _brokerLeadershipMovementConcurrency = null;
  private Integer _clusterLeadershipMovementConcurrency = null;
  public boolean _initialized = Verifier.nondetBoolean();

  /** ARG-V: suitable */
  public Main(boolean initialized,
      Map<Integer, Integer> interBrokerPartitionMovementConcurrency,
      Map<Integer, Integer> intraBrokerPartitionMovementConcurrency,
      Map<Integer, Integer> brokerLeadershipMovementConcurrency,
      Integer clusterLeadershipMovementConcurrency) {
    _initialized = initialized;
    _interBrokerPartitionMovementConcurrency = new HashMap<>(interBrokerPartitionMovementConcurrency);
    _intraBrokerPartitionMovementConcurrency = new HashMap<>(intraBrokerPartitionMovementConcurrency);
    _brokerLeadershipMovementConcurrency = new HashMap<>(brokerLeadershipMovementConcurrency);
    _clusterLeadershipMovementConcurrency = clusterLeadershipMovementConcurrency;
  }

  /**
   * Get the cluster leadership movement concurrency.
   * 
   * @return the cluster leadership movement concurrency. If not initialized or
   *         the concurrency is null, return 0.
   */
  /** ARG-V: suitable */
  public synchronized int getClusterLeadershipMovementConcurrency() {
    if (!_initialized || _clusterLeadershipMovementConcurrency == null) {
      assert _initialized == false; // inline assert generated by ARG-V
      return 0;
    }
    return _clusterLeadershipMovementConcurrency.intValue();
  }

  /** ARG-V: suitable */
  private void sanityCheckValidity() {
    if (_interBrokerPartitionMovementConcurrency.isEmpty()
        || _intraBrokerPartitionMovementConcurrency.isEmpty()
        || _brokerLeadershipMovementConcurrency.isEmpty()) {
      throw new IllegalArgumentException("Broker concurrency is not populated.");
    }
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    boolean initialized = Verifier.nondetBoolean();
    Map<Integer, Integer> interBrokerPartitionMovementConcurrency = new HashMap<>();
    Map<Integer, Integer> intraBrokerPartitionMovementConcurrency = new HashMap<>();
    Map<Integer, Integer> brokerLeadershipMovementConcurrency = new HashMap<>();
    Integer clusterLeadershipMovementConcurrency = Verifier.nondetInt();
    if (clusterLeadershipMovementConcurrency != 0) {
      interBrokerPartitionMovementConcurrency.put(Verifier.nondetInt(), Verifier.nondetInt());
      intraBrokerPartitionMovementConcurrency.put(Verifier.nondetInt(), Verifier.nondetInt());
      brokerLeadershipMovementConcurrency.put(Verifier.nondetInt(), Verifier.nondetInt());
      Main instance = new Main(initialized, interBrokerPartitionMovementConcurrency,
        intraBrokerPartitionMovementConcurrency, brokerLeadershipMovementConcurrency, clusterLeadershipMovementConcurrency);
      instance.sanityCheckValidity();
      int concurrency = instance.getClusterLeadershipMovementConcurrency();
      if (concurrency != 0) {
        assert concurrency == clusterLeadershipMovementConcurrency.intValue();
        assert instance._initialized;
      }
    }

  }
}
