// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class Main {
    /** ARG-V: suitable */
	 public void updateGuideContentById(long id, Map<String, Object> map) throws Exception {
        Object content = map.get("content");
        if(content == null){
            throw new Exception();
        }
        Object contentHtml = map.get("contentHtml");
        if(contentHtml == null){
            throw new Exception();
        }
        map.put("content", (Long)content + id);
        map.put("contentHtml", (Long)contentHtml + id);
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        Main instance=new Main();
        Map<String, Object> map = new HashMap<>();
        long content = Verifier.nondetLong();
        long contentHtml = Verifier.nondetLong();
        map.put("content", content);
        map.put("contentHtml", contentHtml);
        long id = Verifier.nondetLong();
        instance.updateGuideContentById(id, map);
        assert (Long)map.get("content") >= content;
        assert (Long)map.get("contentHtml") >= contentHtml;
      }
}
