// SPDX-FileCopyrightText: Copyright (C) 2017 - 2021 adorsys GmbH & Co. KG @ https://adorsys.com
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*-
 * ---license-start
 * keycloak-config-cli
 * ---
 * Copyright (C) 2017 - 2021 adorsys GmbH & Co. KG @ https://adorsys.com
 * ---
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * ---license-end
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.*;
import java.util.stream.Collectors;

public class Main {
    /** ARG-V: suitable */
	 public void update(String realmName, String roleClientId, String roleName, Map<String, List<String>> clientComposites) {
        removeClientRoleClientComposites(realmName, roleClientId, roleName, clientComposites);
    }

    /** ARG-V: suitable */
	 public void updateClientComposites(
            String realmName,
            String roleClientId,
            String roleName,
            String clientId,
            List<String> composites
    ) {
        List<String> existingClientCompositeNames = findClientRoleClientCompositeNames(realmName, roleClientId, roleName, clientId);

        if (!(Objects.equals(existingClientCompositeNames, composites))) {
			removeClientRoleClientComposites(realmName, roleClientId, roleName, clientId, existingClientCompositeNames,
					composites);
			addClientRoleClientComposites(realmName, roleClientId, roleName, clientId, existingClientCompositeNames,
					composites);
		}
    }

    /** ARG-V: suitable */
	 private List<String> findClientRoleClientCompositeNames(
            String realmName,
            String roleClientId,
            String realmRole,
            String clientId
    ) {
        assert realmName != null && roleClientId != null && realmRole != null && clientId != null; //inline assert generated by ARG-V
        List <String> compositeNames = new ArrayList<>();
        compositeNames.add(realmName + roleClientId);
        compositeNames.add(realmName + roleClientId + realmRole);
        compositeNames.add(realmName + roleClientId + clientId);
        compositeNames.add(realmName + roleClientId + realmRole + clientId);
		return compositeNames;
    }

    /** ARG-V: suitable */
	 private void removeClientRoleClientComposites(
            String realmName,
            String roleClientId,
            String realmRole,
            String clientId,
            Collection<String> existingClientCompositeNames,
            Collection<String> clientCompositesByClient
    ) {
        Set<String> clientRoleCompositesToRemove = new HashSet<>();
        for (String compositeName : existingClientCompositeNames) {
            if (!clientCompositesByClient.contains(compositeName)) {
                clientRoleCompositesToRemove.add(compositeName);
            }
        }
        for (String compositeName : clientRoleCompositesToRemove) {
            existingClientCompositeNames.remove(compositeName);
        }
    }

    /** ARG-V: suitable */
	 private void removeClientRoleClientComposites(
            String realmName,
            String roleClientId,
            String realmRole,
            Map<String, List<String>> clientComposites
    ) {
        Set<String> existingCompositeClients = new HashSet<>();
        existingCompositeClients.addAll(clientComposites.get(null));

        Set<String> compositeClientsToRemove = null;

        Map<String, List<String>> clientCompositeRolesToBeRemoved = estimateClientCompositeRolesToBeRemoved(
                realmName,
                roleClientId,
                realmRole,
                compositeClientsToRemove
        );
    }

    /** ARG-V: suitable */
	 private void addClientRoleClientComposites(
            String realmName,
            String clientRoleId,
            String realmRole,
            String clientId,
            Collection<String> existingClientCompositeNames,
            Collection<String> clientCompositesByClient
    ) {
        Set<String> clientRoleCompositesToAdd = null;
    }

    /** ARG-V: suitable */
	 private Map<String, List<String>> estimateClientCompositeRolesToBeRemoved(
            String realmName,
            String roleClientId,
            String roleName,
            Set<String> compositeClientsToRemove
    ) {
        Map<String, List<String>> existingClientCompositeNames = null;

        Map<String, List<String>> clientRolesToRemove = new HashMap<>();
		return clientRolesToRemove;
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        Main instance=new Main();
        String realmName=Verifier.nondetString();
        String roleClientId=Verifier.nondetString();
        String roleName=Verifier.nondetString();
        String clientId=Verifier.nondetString();
        List<String> composites=instance.findClientRoleClientCompositeNames(realmName, roleClientId, roleName, clientId);
        Map<String, List<String>> clientComposites=new HashMap<>();
        clientComposites.put(clientId, composites);
        instance.update(realmName, roleClientId, roleName, clientComposites);
        instance.updateClientComposites(realmName, roleClientId, roleName, clientId, composites);
        assert composites.size() == 4;
    }
}
