// SPDX-FileCopyrightText: Copyright Camunda Services GmbH
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright Camunda Services GmbH and/or licensed to Camunda Services GmbH
 * under one or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information regarding copyright
 * ownership. Camunda licenses this file to you under the Apache License,
 * Version 2.0; you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;

/**
 * JUEL-specific implementation of an {@link ExpressionManager}.
 *
 * @author Tom Baeyens
 * @author Dave Syer
 * @author Frederik Heremans
 */
public class Main {

  protected Map<String, Method> functions = new HashMap<String, Method>();
  protected Map<Object, Object> beans = null;
  public volatile boolean initialized = false;

  /** ARG-V: suitable */
  public Main() {
    this(null);
  }

  /** ARG-V: suitable */
  public Main(Map<Object, Object> beans) {
    this.beans = beans;
  }

  /** ARG-V: suitable */
  public void addFunction(String name, Method function) throws Exception {
    function.invoke(this);
    functions.put(name, function);
  }

  /** ARG-V: suitable */
  public void ensureInitialized() {
    if (!initialized) {
      synchronized (this) {
        if (!initialized) {
          initialized = true;
        }
      }
    }
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main((java.util.Map<java.lang.Object, java.lang.Object>) null);
    Class<?> clazz = instance.getClass();
    Method method = clazz.getMethod("ensureInitialized");
    assert method != null;
    instance.addFunction(Verifier.nondetString(), method);
    assert instance.initialized == true;
  }
}

