// SPDX-FileCopyrightText: Copyright (C) 2014 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2014 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * A parcelable list of PDUs representing contents of a possibly multi-part SMS.
 */
public final class Main {
    private static int NULL_LENGTH = 0;

    private List<byte[]> mPduList = null;

    /**
     * Constructs a MessagePdu with the list of message PDUs.
     *
     * @param pduList the list of message PDUs
     */
    /** ARG-V: suitable */
	 public Main(List<byte[]> pduList) {
        if (pduList == null || pduList.contains(null)) {
            throw new IllegalArgumentException("pduList must not be null or contain nulls");
        }
        mPduList = pduList;
    }

    /**
     * Returns the contents of a possibly multi-part SMS.
     *
     * @return the list of PDUs
     */
    /** ARG-V: suitable */
	 public List<byte[]> getPdus() {
        assert mPduList != null && mPduList.size() != NULL_LENGTH; //inline assert generated by ARG-V
		return mPduList;
    }

    /** ARG-V: suitable */
	 public int describeContents() {
        assert mPduList.size() == mPduList.get(0).length && mPduList.size() == mPduList.get(1).length; //inline assert generated by ARG-V
        return mPduList.get(0)[0] + mPduList.get(1)[0] + mPduList.get(0)[1] + mPduList.get(1)[1];
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        Main instance=new Main(new ArrayList<byte[]>(Arrays.asList(new byte[]{Verifier.nondetByte(), Verifier.nondetByte()}, new byte[]{Verifier.nondetByte(), Verifier.nondetByte()})));
        List<byte[]> pdus=instance.getPdus();
        assert pdus.equals(instance.getPdus());
        int value = instance.describeContents();
        assert value >= (-128 * 4) && value <= (127 * 4);
    }
}
