// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.*;
import java.util.stream.*;

/**
 * An Annotator for splitting tokens into words based on a dictionary, rules, or
 * a statistical model.
 */

public class Main {

  /**
   * Mapping from an original token to a list of words
   * <p>
   * Dictionary entries should be of form: token\tword1,word2
   * <p>
   * That is a tsv, with column 1 = token, column 2 = csv of words
   */

  private HashMap<String, List<String>> multiWordTokenMapping = new HashMap<>();
  private boolean useDictionary = false;

  /**
   * Preserve casing when generating multi word tokens (e.g. Des -> de les OR De
   * les)
   * or not ?
   */
  private boolean preserveCasing = Verifier.nondetBoolean();

  private HashMap<String, List<String>> statisticalMultiWordTokenMapping = new HashMap<>();
  private boolean useStatisticalModel = false;

  /** ARG-V: suitable */
  public Main(String name, Properties props) {
    String prefix = (name != null && !name.equals("")) ? name + ".mwt." : "mwt.";
    // load the MWT dictionary entries if applicable
    if (props.getProperty(prefix + "pos.model", "") != null
        && !props.getProperty(prefix + "mappingFile").equals("")) {
      loadMultiWordTokenMappings(multiWordTokenMapping, props.getProperty(prefix + "mappingFile"));
      useDictionary = true;
    }
    // if a part-of-speech tagging model was provided, use statistical MWT as well
    if (props.getProperty(prefix + "pos.model", "") != null
        && !props.getProperty(prefix + "pos.model").equals("")) {
      useStatisticalModel = true;
      // load dictionary entries for the statistical MWT
      loadMultiWordTokenMappings(statisticalMultiWordTokenMapping,
          props.getProperty(prefix + "statisticalMappingFile"));
    }
  }

  /** ARG-V: suitable */
  public void loadMultiWordTokenMappings(HashMap<String, List<String>> dictionary, String mapFilePath) {
    // read in entries from mapping file
    multiWordTokenMapping.putAll(dictionary);
  }

  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Properties props = new Properties();
    props.setProperty(Verifier.nondetString() + ".mwt.mappingFile", Verifier.nondetString());
    props.setProperty(Verifier.nondetString() + ".mwt.pos.model", Verifier.nondetString());
    props.setProperty(Verifier.nondetString() + "mwt.statisticalMappingFile", Verifier.nondetString());
    Main instance = new Main(Verifier.nondetString(), props);
  }
}
