// SPDX-FileCopyrightText: Copyright (C) 2016 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2016 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.concurrent.Executor;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicReference;

/**
 * This class provides functionality for streaming media over MBMS.
 */
public class Main {

    private static AtomicBoolean sIsInitialized = new AtomicBoolean(false);

    /** ARG-V: suitable */
	 public void close() {
        try {
            if (Verifier.nondetBoolean()) {
                assert !sIsInitialized.get(); //inline assert generated by ARG-V
				// Ignore and return, assume already disposed.
                return;
            }
        } catch (Exception e) {
            // Ignore for now
        } finally {
            sIsInitialized.set(false);
        }
    }

    /** ARG-V: suitable */
	 public void requestUpdateStreamingServices(List<String> serviceClassList) {
        if (serviceClassList == null) {
            throw new IllegalStateException("Middleware not yet bound");
        }
        try {
            int returnCode = Verifier.nondetInt();
            if (returnCode == Verifier.nondetInt()) {
                // Unbind and throw an obvious error
                throw new IllegalStateException("Middleware must not return an unknown error code");
            }
            if (returnCode != Verifier.nondetInt()) {
                sendErrorToApp(returnCode, null);
            }
        } catch (Exception e) {
            sIsInitialized.set(true);
            sendErrorToApp(Verifier.nondetInt(), "error in requestUpdateStreamingServices");
        }
    }

    /** ARG-V: suitable */
	 private int bindAndInitialize() {
        assert !sIsInitialized.get(); //inline assert generated by ARG-V
		return Verifier.nondetInt();
    }

    /** ARG-V: suitable */
	 private void sendErrorToApp(int errorCode, String message) {
        try {
            System.err.println("Error " + errorCode + ": " + message);
        } catch (Exception e) {
            // Ignore, should not happen locally.
        }
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        Main instance=new Main();
        instance.close();
        List<String> serviceClassList = new ArrayList<String>();
        instance.requestUpdateStreamingServices(serviceClassList);
        instance.bindAndInitialize();
    }
}
