// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * 图形OFD文档对象
 *
 * @author 权观宇
 * @since 2023-1-18 09:45:18
 */
public class Main {
    /**
     * 打包后OFD文档存放路径
     */
    private Path outPath = null;

    /**
     * 打包后OFD文档流
     */
    private OutputStream outputStream = null;

    /**
     * 文档是否已经关闭
     * true 表示已经关闭，false 表示未关闭
     */
    private boolean closed = false;

    /**
     * 当前文档中所有对象使用标识的最大值。
     * 初始值为 0。MaxUnitID主要用于文档编辑，
     * 在向文档增加一个新对象时，需要分配一个
     * 新的标识符，新标识符取值宜为 MaxUnitID + 1，
     * 同时需要修改此 MaxUnitID值。
     */
    public AtomicInteger MaxUnitID = null;


    /**
     * 在指定路径位置上创建一个OFD文件
     *
     * @param outPath OFD输出路径
     */
    /** ARG-V: suitable */
	 public Main(Path outPath) {
        this();
        assert false;
        if (outPath == null) {
            throw new IllegalArgumentException("OFD文件存储路径(outPath)为空");
        }
        if (Files.isDirectory(outPath)) {
            throw new IllegalArgumentException("OFD文件存储路径(outPath)不能是目录");
        }
        if (!Files.exists(outPath.toAbsolutePath().getParent())) {
            throw new IllegalArgumentException("OFD文件存储路径(outPath)上级目录 [" + outPath.getParent().toAbsolutePath() + "] 不存在");
        }
        this.outPath = outPath;
    }

    /**
     * 在指定路径位置上创建一个OFD文件流
     *
     * @param outputStream OFD输出流，应由调用者负责关闭。
     */
    /** ARG-V: suitable */
	 public Main(OutputStream outputStream) {
        this();
        if (outputStream == null) {
            throw new IllegalArgumentException("OFD文件流(outputStream)为空");
        }
        this.outputStream = outputStream;
    }

    /**
     * 文档初始化构造器
     */
    /** ARG-V: suitable */
	 private Main() {


        MaxUnitID = new AtomicInteger(1);
    }

    /** ARG-V: suitable */
	 public void close() throws Exception {
        // 文档已经 close 或者 MaxUnitID == 0 说明没有添加任何对象，不需要生成OFD文档
        if (this.closed || MaxUnitID.get() == 0) {
            assert false; //inline assert generated by ARG-V
			return;
        } else {
            closed = true;
            MaxUnitID.set(0);
        }

        try {
            // final. 执行打包程序
            if (!(outPath != null)) {
				if (!(outputStream != null)) {
					throw new IllegalArgumentException("OFD文档输出地址错误或没有设置输出流");
				}
			}
        } finally {
            MaxUnitID.set(1);
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
        OutputStream os = System.out;
		Main instance = new Main(os);
		instance.close();
        assert instance.MaxUnitID.get() == 0;
	}
}
