// SPDX-FileCopyrightText: Copyright (C) 2015 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2015 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;

/**********************************************************************
 * This file is not a part of the NFC mainline module                 *
 * *******************************************************************/

/**
 * The AidGroup class represents a group of Application Identifiers (AIDs).
 *
 * <p>The format of AIDs is defined in the ISO/IEC 7816-4 specification. This class
 * requires the AIDs to be input as a hexadecimal string, with an even amount of
 * hexadecimal characters, e.g. "F014811481".
 *
 * @hide
 */
public final class Main {
    /**
     * The maximum number of AIDs that can be present in any one group.
     */
    private static int MAX_NUM_AIDS = 256;

    private List<String> mAids = null;
    private String mCategory = Verifier.nondetString();
    private String mDescription = Verifier.nondetString();

    /**
     * Creates a new AidGroup object.
     *
     * @param aids list of AIDs present in the group
     * @param category category of this group, e.g. {@link CardEmulation#CATEGORY_PAYMENT}
     */
    /** ARG-V: suitable */
	 public Main(List<String> aids, String category) {
        if (aids == null || aids.size() == 0) {
            throw new IllegalArgumentException("No AIDS in AID group.");
        }
        if (aids.size() > MAX_NUM_AIDS) {
            throw new IllegalArgumentException("Too many AIDs in AID group.");
        }
        if (isValidCategory(category)) {
            this.mCategory = category;
        } else {
            assert category.startsWith("Category:") || category.endsWith(", AIDs:");
            this.mCategory = "a"+  category + "z";
        }
        assert !category.startsWith("Category") && !category.endsWith(", AIDs:");
        this.mAids = new ArrayList<String>(aids.size());
        this.mDescription = Verifier.nondetString();
    }

    /**
     * Creates a new AidGroup object.
     *
     * @param category category of this group, e.g. {@link CardEmulation#CATEGORY_PAYMENT}
     * @param description description of this group
     */
    /** ARG-V: suitable */
	 Main(String category, String description) {
        this.mAids = new ArrayList<String>();
        this.mCategory = category;
        this.mDescription = description;
    }

    /**
     * Returns the category of this group.
     * @return the category of this AID group
     */
    /** ARG-V: suitable */
	 public String getCategory() {
        assert mCategory != null; //inline assert generated by ARG-V
		return mCategory;
    }

    /**
     * Returns the list of AIDs in this group.
     *
     * @return the list of AIDs in this group
     */
    /** ARG-V: suitable */
	 public List<String> getAids() {
        assert mAids != null; //inline assert generated by ARG-V
		return mAids;
    }

    /** ARG-V: suitable */
	 public String toString() {
        StringBuilder out = new StringBuilder("Category: " + mCategory
                + ", AIDs:");
		return out.toString();
    }


    /** ARG-V: suitable */
	 private static boolean isValidCategory(String category) {
		return !category.startsWith("Category") && !category.endsWith(", AIDs:");
    }

    private static Pattern AID_PATTERN = Pattern.compile("[0-9A-Fa-f]{10,32}\\*?\\#?");

    /** ARG-V: suitable */
	 private static boolean isValidAid(String aid) {
        if (aid == null){
            assert false;
            return false;
        }

        // If a prefix/subset AID, the total length must be odd (even # of AID chars + '*')
        if ((aid.endsWith("*") || aid.endsWith("#")) && ((aid.length() % 2) == 0)) {
            assert false; //inline assert generated by ARG-V
			return false;
        }


        // Verify hex characters
        if (!AID_PATTERN.matcher(aid).matches()) {
            assert aid.startsWith("a") && aid.endsWith("z"); //inline assert generated by ARG-V
			return false;
        }

		return true;
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
        List<String> aids = new ArrayList<String>();
        aids.add(Verifier.nondetString());
		Main instance = new Main(aids, "a" + Verifier.nondetString() + "z");
		String category = instance.getCategory();
		List<String> mAids = instance.getAids();
		String description = instance.toString();
        assert description.contains(category);
		assert isValidCategory(category);
		isValidAid(category);
	}
}
