// SPDX-FileCopyrightText: Copyright (C) 2021 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/**
 * Copyright (C) 2021 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.concurrent.Executor;
import java.util.function.Consumer;

public final class Main {

    private static Object sLock = new Object();

    private boolean mInternalListenerAttached = false;
    private boolean mCrossWindowBlurEnabled = Verifier.nondetBoolean();


    /** ARG-V: suitable */
	 public boolean isCrossWindowBlurEnabled() {
        synchronized (sLock) {
            attachInternalListenerIfNeededLocked();
            assert true; //inline assert generated by ARG-V
			return mCrossWindowBlurEnabled;
        }
    }

    /** ARG-V: suitable */
	 public void addListener(Executor executor, Consumer<Boolean> listener) {
        synchronized (sLock) {
            attachInternalListenerIfNeededLocked();
            notifyListener(listener, executor, mCrossWindowBlurEnabled);
        }
    }


    /** ARG-V: suitable */
	 private void attachInternalListenerIfNeededLocked() {
        if (!mInternalListenerAttached) {
            try {
                mInternalListenerAttached = true;
                mCrossWindowBlurEnabled = mInternalListenerAttached;
            } catch (Exception e) {
            }
        }
    }

    /** ARG-V: suitable */
	 private void notifyListener(Consumer<Boolean> listener, Executor executor, boolean enabled) {
        executor.execute(() -> listener.accept(enabled));
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        Main instance=new Main();
        instance.isCrossWindowBlurEnabled();
        Executor executor = command -> command.run();
        Consumer<Boolean> consumer = value -> {assert value;};
        instance.addListener(executor, consumer);
    }
}
