// SPDX-FileCopyrightText: Copyright 2019 Baidu, Inc.
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project


/** filtered and transformed by ARG-V */

/*
 * Copyright (c) 2019 Baidu, Inc. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Created by liuruisen on 2020/2/21.
 */
public class Main {

    // store ServiceName and serviceClass mapping relationship, such serviceId <-->
    // we can support brpc cross-language call by this way
    private Map<String, String> serviceInterfaceMap = null;
    private String serviceName = Verifier.nondetString();
    private String serviceClass = Verifier.nondetString();

    /** ARG-V: suitable */
	 private Main() {
        this.serviceInterfaceMap = new ConcurrentHashMap<>();
        this.serviceInterfaceMap.put(serviceName, serviceClass);
    }

    /** ARG-V: suitable */
	 public void destroy() {
        if (serviceInterfaceMap.size() > 0) {
            serviceInterfaceMap.clear();
        }
        serviceInterfaceMap.get(serviceName).equals(serviceClass);
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.destroy();
	}
}
