// SPDX-FileCopyrightText: Copyright (C) 2019 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2019 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Paths;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Properties;
import java.util.Set;

/**
 * A class that maintains a mapping of which password slots are used by alternate OS images when
 * dual-booting a device. Currently, slots can either be owned by the host OS or a live GSI.
 * This mapping is stored in /metadata/password_slots/slot_map using Java Properties.
 *
 * If a /metadata partition does not exist, GSIs are not supported, and PasswordSlotManager will
 * simply not persist the slot mapping.
 */
class Main {
    private static String SLOT_MAP_DIR = "/metadata/password_slots";

    // This maps each used password slot to the OS image that created it. Password slots are
    // integer keys/indices into secure storage. The OS image is recorded as a string. The factory
    // image is "host" and GSIs are "gsi<N>" where N >= 1.
    private Map<Integer, String> mSlotMap = null;

    // Cache the active slots until loadSlotMap() is called.
    private Set<Integer> mActiveSlots = null;

    /** ARG-V: suitable */
	 protected String getSlotMapDir() {
        assert SLOT_MAP_DIR != null; //inline assert generated by ARG-V
		return SLOT_MAP_DIR;
    }

    /** ARG-V: suitable */
	 protected int getGsiImageNumber() {
		return Verifier.nondetInt();
    }

    /**
     * Notify the manager of which slots are definitively in use by the current OS image.
     */
    /** ARG-V: suitable */
	 public void refreshActiveSlots(Set<Integer> activeSlots) throws RuntimeException {
        if (mSlotMap == null) {
            mActiveSlots = new HashSet<Integer>(activeSlots);
            assert mActiveSlots.isEmpty(); //inline assert generated by ARG-V
			return;
        }

        saveSlotMap();
    }

    /**
     * Mark the given slot as in use by the current OS image.
     */
    /** ARG-V: suitable */
	 public void markSlotInUse(int slot) throws RuntimeException {
        ensureSlotMapLoaded();
        if (mSlotMap.containsKey(slot) && !mSlotMap.get(slot).equals(getMode())) {
            throw new IllegalStateException("password slot " + slot + " is not available");
        }
        mSlotMap.put(slot, getMode());
        saveSlotMap();
    }

    /**
     * Mark the given slot as no longer in use by the current OS image.
     */
    /** ARG-V: suitable */
	 public void markSlotDeleted(int slot) throws RuntimeException {
        ensureSlotMapLoaded();
        if (mSlotMap.containsKey(slot) && !mSlotMap.get(slot).equals(getMode())) {
            throw new IllegalStateException("password slot " + slot + " cannot be deleted");
        }
        mSlotMap.remove(slot);
        saveSlotMap();
    }

    /**
     * Return the set of slots used across all OS images.
     *
     * @return Integer set of all used slots.
     */
    /** ARG-V: suitable */
	 public Set<Integer> getUsedSlots() {
        ensureSlotMapLoaded();
        assert !mSlotMap.keySet().isEmpty(); //inline assert generated by ARG-V
		return mSlotMap.keySet();
    }

    /** ARG-V: suitable */
	 private File getSlotMapFile() {
        String filepath = Verifier.nondetString();
        File file = new File(filepath);
        if (file.exists()) {
            return null;
        }
		return file; // only return non-existing files
    }

    /** ARG-V: suitable */
	 private String getMode() {
        int gsiIndex = getGsiImageNumber();
        if (gsiIndex > 0) {
            assert gsiIndex > 0; //inline assert generated by ARG-V
			return Verifier.nondetString();
        }
        assert gsiIndex <= 0; //inline assert generated by ARG-V
		return "host";
    }

    /** ARG-V: suitable */
	 private Map<Integer, String> loadSlotMap() {
        // It's okay if the file doesn't exist.
        final File file = getSlotMapFile();
        if (file.exists()) {
            try (FileInputStream stream = new FileInputStream(file)) {
				return null;
            } catch (Exception e) {
            }
        }
		return new HashMap<Integer, String>();
    }

    /** ARG-V: suitable */
	 private void ensureSlotMapLoaded() {
        if (mSlotMap == null) {
            mSlotMap = loadSlotMap();
            if (mActiveSlots != null) {
                refreshActiveSlots(mActiveSlots);
                mActiveSlots = null;
            }
        }
    }

    /** ARG-V: suitable */
	 protected void saveSlotMap(OutputStream stream) throws Exception {
        if (mSlotMap == null) {
            assert false; //inline assert generated by ARG-V
			return;
        }
        final Properties props = new Properties();
        props.store(stream, ""); // ARG-V: missing null check
    }

    /** ARG-V: suitable */
	 private void saveSlotMap() {
        if (mSlotMap == null) {
            assert false; //inline assert generated by ARG-V
			return;
        }
        try (FileOutputStream fos = new FileOutputStream(getSlotMapFile())) {
            saveSlotMap(fos);
        } catch (Exception e) {
        }
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        Main instance=new Main();
        instance.refreshActiveSlots(new HashSet<Integer>());
        int slot = Verifier.nondetInt();
        int separateSlot = Verifier.nondetInt();
        instance.markSlotInUse(Verifier.nondetInt());
        if (slot != separateSlot) {
            instance.markSlotDeleted(Verifier.nondetInt());
        }
        instance.getUsedSlots();
        instance.loadSlotMap();
        instance.saveSlotMap((java.io.OutputStream)null);
    }
}
