// SPDX-FileCopyrightText: Copyright (C) 2020 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project
/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.concurrent.Executor;

/**
 * The ImsService implements this class to manage the creation and destruction of
 * {@link SipDelegate}s.
 *
 * {@link SipDelegate}s allow the ImsService to forward SIP traffic generated and consumed by IMS
 * applications as a delegate to the associated carrier's IMS Network in order to support using a
 * single IMS registration for all MMTEL and RCS signalling traffic.
 * @hide
 */
public class Main {
    private static String LOG_TAG = "SipTransportIB";

    private Executor mBinderExecutor = null;
    /**
     * Create a new SipTransport.
     * <p>
     * Method stubs called from the framework will be called asynchronously. To specify the
     * {@link Executor} that the methods stubs will be called, use
     * {@link SipTransportImplBase#SipTransportImplBase(Executor)} instead.
     */
    /** ARG-V: suitable */
	 public Main() {
    }

    /**
     * Create an implementation of SipTransportImplBase.
     *
     * @param executor The executor that remote calls from the framework will be called on. This
     *                 includes the methods here as well as the methods in {@link SipDelegate}.
     */
    /** ARG-V: suitable */
	 public Main(Executor executor) {
        if (executor == null) {
            throw new IllegalArgumentException("executor must not be null");
        }

        mBinderExecutor = executor;
    }

    /**
     * Set default Executor from ImsService.
     * @param executor The default executor for the framework to use when executing the methods
     * overridden by the implementation of SipTransport.
     * @hide
     */
    /** ARG-V: suitable */
	 public final void setDefaultExecutor(Executor executor) {
        if (mBinderExecutor == null) {
            mBinderExecutor = executor;
        }
        executor.execute(LOG_TAG::length);
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
        Executor executor = command -> command.run();
		Main instance = new Main(executor);
		instance.setDefaultExecutor(executor);
	}
}
