// SPDX-FileCopyrightText: Copyright (c) 2012 LinkedIn Corp.
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
   Copyright (c) 2012 LinkedIn Corp.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
import org.sosy_lab.sv_benchmarks.Verifier;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Configuration for rest.li servers.
 *
 * @author dellamag
 */
public class Main {

  /**
   * Default value for the maximum number of individual requests allowed in a
   * multiplexed request.
   */


  public Set<String> _resourcePackageNames = new HashSet<>();

  /**
   * Constructor.
   */
  /** ARG-V: suitable */
  public Main() {
    this(Collections.emptyMap());
  }

  /**
   * @param mapConfig not currently used
   * @deprecated Map of config properties is not supported. There is no
   *             replacement.
   */
  /** ARG-V: suitable */
  public Main(final Map<String, Object> mapConfig) {
  }


  /**
   * @param commaDelimitedResourcePackageNames comma-delimited package names list
   */
  /** ARG-V: suitable */
  public void setResourcePackageNames(final String commaDelimitedResourcePackageNames) {
    if (commaDelimitedResourcePackageNames != null && !"".equals(commaDelimitedResourcePackageNames.trim())) {
      _resourcePackageNames.clear();

      // The commas could have spaces around them like com.linkedin.foo ,
      // com.linkedin.bar.
      // For such cases, trim those spaces.
      addResourcePackageNames(
          Arrays.stream(commaDelimitedResourcePackageNames.split(","))
              .map(String::trim)
              .collect(Collectors.toSet()));
    }
  }


  /**
   * @param packageNames collection of package names to be scanned
   */
  /** ARG-V: suitable */
  public void addResourcePackageNames(final Collection<String> packageNames) {
    _resourcePackageNames.addAll(packageNames);
  }


  /** This main was generated by ARG-V */
  public static void main(String[] args) throws Exception {
    Main instance = new Main((java.util.Map<java.lang.String, java.lang.Object>) null);
    String commaDelimitedResourcePackageNames = Verifier.nondetString();
    instance.setResourcePackageNames(commaDelimitedResourcePackageNames);
    assert commaDelimitedResourcePackageNames.length() == 0 || instance._resourcePackageNames.size() < (commaDelimitedResourcePackageNames.length());
  }
}
