// SPDX-FileCopyrightText: Copyright (C) 2010 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2010 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.HashMap;


public class Main {

    // Please add newly defined type constants to the end of the list,
    // and modify checkTypeValidity() accordingly.

    /**
     * The registration has already been done by another account ID.
     */
    public static int TYPE_ALREADY_REGISTERED_BY_ANOTHER_ACCOUNT = 1;
    /**
     * The rights need to be removed completely.
     */
    public static int TYPE_REMOVE_RIGHTS = 2;
    /**
     * The rights have been removed.
     */
    public static int TYPE_RIGHTS_REMOVED = 6;

    // Add more type constants here...

    /**
     * Creates a <code>DrmInfoEvent</code> object with the specified parameters.
     *
     * @param uniqueId Unique session identifier.
     * @param type Type of the event. Must be any of the event types defined above,
     * or the constants defined in {@link DrmEvent}.
     * @param message Message description. It can be null.
     */
    /** ARG-V: suitable */
	 public Main(int uniqueId, int type, String message) {
        checkTypeValidity(type);
    }

    /**
     * Creates a <code>DrmInfoEvent</code> object with the specified parameters.
     *
     * @param uniqueId Unique session identifier.
     * @param type Type of the event. Must be any of the event types defined above,
     * or the constants defined in {@link DrmEvent}
     * @param message Message description. It can be null.
     * @param attributes Attributes for extensible information. Could be any
     * information provided by the plug-in.
     */
    /** ARG-V: suitable */
	 public Main(int uniqueId, int type, String message,
                            HashMap<String, Object> attributes) {
        checkTypeValidity(type);
    }

    /*
     * Check the validity of the given type.
     * To overcome a design flaw, we need also accept the type constants
     * defined in super class, DrmEvent.
     */
    /** ARG-V: suitable */
	 private void checkTypeValidity(int type) {
        if (type < TYPE_ALREADY_REGISTERED_BY_ANOTHER_ACCOUNT ||
            type > TYPE_RIGHTS_REMOVED) {

            if (Verifier.nondetBoolean()) {
                final String msg = "Unsupported type: " + type;
                throw new IllegalArgumentException(msg);
            }
            return;
        }
        assert type <= TYPE_RIGHTS_REMOVED && type >= TYPE_ALREADY_REGISTERED_BY_ANOTHER_ACCOUNT; 
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        int type = Verifier.nondetInt();
        Main instance=new Main(TYPE_REMOVE_RIGHTS,type,Verifier.nondetString());
        instance.checkTypeValidity(type);

    }
}

