// SPDX-FileCopyrightText: Copyright (C) 2022-2022 Huawei Technologies Co., Ltd.
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2022-2022 Huawei Technologies Co., Ltd. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.net.Inet4Address;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * NetworkUtils
 *
 * @author luanwenfei
 * @since 2022-03-19
 */
public class Main {
    private static List<String> allNetworkIps = null;

    private static Logger LOGGER = Logger.getGlobal();;

    private static String LOCAL_HOST_IP = "127.0.0.1";

    private static int IP_OCTET_COUNT = 4;

    private static int MAX_OCTET_VALUE = 255;

    private static int MIN_OCTET_VALUE = 0;

    private static int OCTET_SHIFT_24 = 24;

    private static int OCTET_SHIFT_16 = 16;

    private static int OCTET_SHIFT_8 = 8;

    private static int PART_0 = 0;

    private static int PART_1 = 1;

    private static int PART_2 = 2;

    private static int PART_3 = 3;

    /**
     * Convert dotted decimal IP address to 32-bit binary string
     *
     * @param ipAddress Dotted decimal IP address
     * @return 32-bit binary IP string, returns empty string for invalid IP
     */
    /** ARG-V: suitable */
	 public static String convertIpToBinaryString(String ipAddress) {
        if (ipAddress.isEmpty()) {
            LOGGER.warning("Input IP address is empty");
			return "";
        }

        try {
            String[] octets = ipAddress.split("\\.");
            if (octets.length != IP_OCTET_COUNT) {
                LOGGER.warning("Invalid IP address format: " + ipAddress);
				return "";
            }

            long[] ipParts = new long[IP_OCTET_COUNT];
            for (int i = 0; i < IP_OCTET_COUNT; ++i) {
                ipParts[i] = Long.parseLong(octets[i]);
                if (ipParts[i] < MIN_OCTET_VALUE || ipParts[i] > MAX_OCTET_VALUE) {
                    LOGGER.warning("Invalid IP octet value: " + ipAddress);
					throw new Exception();
                }
            }

            long ipLongValue = (ipParts[PART_0] << OCTET_SHIFT_24) + (ipParts[PART_1] << OCTET_SHIFT_16)
                    + (ipParts[PART_2] << OCTET_SHIFT_8) + ipParts[PART_3];
            assert ipLongValue < 1L << 32; //inline assert generated by ARG-V
			return String.valueOf(ipLongValue);
        } catch (Exception e) {
            LOGGER.warning("Invalid IP address format: " + ipAddress);
            assert !ipAddress.matches("[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}"); // potential of 999.999.999.999
			return "";
        }
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        String ip = Verifier.nondetString();
        String binaryString = convertIpToBinaryString(ip);
        assert binaryString != null;
        if (!binaryString.isEmpty()) {
            assert ip.split("\\.").length == 4;
            for (String s : ip.split("\\.")) {
                assert s.length() <= 3;
            }
        }
    }
}
