// SPDX-FileCopyrightText: Copyright (C) 2020 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Helper for querying shortcuts.
 */
public class Main {
    private static String TAG = "ShortcutHelper";

    // Key: packageName|userId Value: <shortcutId, notifId>
    public HashMap<String, HashMap<String, String>> mActiveShortcutBubbles = new HashMap<>();
    public boolean mShortcutChangedCallbackRegistered = Verifier.nondetBoolean();

    /** ARG-V: suitable */
	 private void onShortcutRemoved(String packageUserKey, String shortcutId) {
        HashMap<String, String> shortcutBubbles = mActiveShortcutBubbles.get(packageUserKey);
        ArrayList<String> bubbleKeysToRemove = new ArrayList<>();
        if (shortcutBubbles != null) {
            if (shortcutBubbles.containsKey(shortcutId)) {
                bubbleKeysToRemove.add(shortcutBubbles.get(shortcutId));
                shortcutBubbles.remove(shortcutId);
                if (shortcutBubbles.isEmpty()) {
                    mActiveShortcutBubbles.remove(packageUserKey);
                    unregisterCallbackIfNeeded();
                }
            }
            notifyNoMan(bubbleKeysToRemove);
            assert mShortcutChangedCallbackRegistered == false;
        }
    }

    /** ARG-V: suitable */
	 private void registerCallbackIfNeeded() {
        if (!mShortcutChangedCallbackRegistered) {
            mShortcutChangedCallbackRegistered = true;
        }
    }

    /** ARG-V: suitable */
	 private void unregisterCallbackIfNeeded() {
        if (mShortcutChangedCallbackRegistered && mActiveShortcutBubbles.isEmpty()) {
            mShortcutChangedCallbackRegistered = false;
        }
    }

    /** ARG-V: suitable */
	 void destroy() {
        if (mShortcutChangedCallbackRegistered) {
            mShortcutChangedCallbackRegistered = false;
        }
    }

    /** ARG-V: suitable */
	 private void notifyNoMan(List<String> bubbleKeysToRemove) {
        // Let NoMan know about the updates
        for (int i = 0; i < bubbleKeysToRemove.size(); i++) {
            // update flag bubble
            String bubbleKey = bubbleKeysToRemove.get(i);
            mActiveShortcutBubbles.remove(bubbleKey);
        }
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        Main instance=new Main();
        String packageUserKey = Verifier.nondetString();
        String shortcutId = Verifier.nondetString();
        instance.mActiveShortcutBubbles.put(packageUserKey, new HashMap<String, String>());
        instance.mActiveShortcutBubbles.get(packageUserKey).put(shortcutId, Verifier.nondetString());
        instance.onShortcutRemoved(Verifier.nondetString(),shortcutId);
        instance.registerCallbackIfNeeded();
        instance.unregisterCallbackIfNeeded();        
        assert instance.mShortcutChangedCallbackRegistered == false;
        instance.destroy();
    }
}
