// SPDX-FileCopyrightText: Copyright (C) 2014-2017 Kotcrab <contact(a)kotcrab.com>
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;

/** @author Kotcrab */
public class Main {
	private static String VIS_DEFAULT_PREFS_NAME = "com.kotcrab.vis.ui.widget.file.filechooser_favorites";
	private static String defaultPrefsName = VIS_DEFAULT_PREFS_NAME;

	private String prefsName = null;

	/** ARG-V: suitable */
	 public Main () {
		this(defaultPrefsName);
	}

	/** ARG-V: suitable */
	 public Main (String prefsName) {
		this.prefsName = prefsName;
		checkIfUsingDefaultName();
	}

	/** ARG-V: suitable */
	 public boolean checkIfUsingDefaultName () {
		if (defaultPrefsName == null) throw new IllegalStateException("defaultPrefsName can't be null");
		if (this.prefsName.equals(defaultPrefsName)){
			return true;
		}
		return false;
	}

	/** ARG-V: suitable */
	 public static void setDefaultPrefsName (String prefsName) {
		if (prefsName == null) throw new IllegalStateException("prefsName can't be null");
		defaultPrefsName = prefsName;
	}

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {

		String prefsName = Verifier.nondetString();
		Main instance = new Main(prefsName);
		if (!prefsName.equals("com.kotcrab.vis.ui.widget.file.filechooser_favorites") && !prefsName.equals("")){
			assert !instance.checkIfUsingDefaultName();
			setDefaultPrefsName("");
			assert !instance.checkIfUsingDefaultName();
		}
	}

}
