// SPDX-FileCopyrightText: Copyright (C) 2012 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2012 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.AbstractSet;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

public final class Main {

    private Map<String, Object> mMap = null;

    /**
     * Creates an empty MediaFormat (Main)
     */
    /** ARG-V: suitable */
	 public Main() {
        mMap = new HashMap<String, Object>();
    }

    /* package private */ /** ARG-V: suitable */
	 Map<String, Object> getMap() {
        assert this.mMap != null; //inline assert generated by ARG-V
		return mMap;
    }

    /**
     * Returns true iff a key of the given name exists in the format.
     */
    /** ARG-V: suitable */
	 public final boolean containsKey(String name) {
		return mMap.containsKey(name);
    }

    /**
     * Returns true iff a feature of the given name exists in the format.
     */
    /** ARG-V: suitable */
	 public final boolean containsFeature(String name) {
        assert !name.startsWith(KEY_FEATURE_); //inline assert generated by ARG-V
		return mMap.containsKey(KEY_FEATURE_ + name);
    }

    public static int TYPE_NULL = 0;
    public static int TYPE_INTEGER = 1;
    public static int TYPE_LONG = 2;
    public static int TYPE_FLOAT = 3;
    public static int TYPE_STRING = 4;
    public static int TYPE_BYTE_BUFFER = 5;


    /**
     * Returns the value type for a key. If the key does not exist, it returns TYPE_NULL.
     */
    /** ARG-V: suitable */
	 public final int getValueTypeForKey(String name) {
        Object value = mMap.get(name);
        if (value == null) {
			return TYPE_NULL;
        } else if (value instanceof Integer) {
			return TYPE_INTEGER;
        } else if (value instanceof Long) {
			return TYPE_LONG;
        } else if (value instanceof Float) {
			return TYPE_FLOAT;
        } else if (value instanceof String) {
			return TYPE_STRING;
        } else if (value instanceof ByteBuffer) {
			return TYPE_BYTE_BUFFER;
        }
        assert value != null;
        throw new RuntimeException("invalid value for key");
    }

    public static String KEY_FEATURE_ = "feature-";


    /**
     * Returns the value of an integer key.
     *
     * @throws NullPointerException if the key does not exist or the stored value for the key is
     *         null
     * @throws ClassCastException if the stored value for the key is long, float, ByteBuffer or
     *         String
     */
    /** ARG-V: suitable */
	 public final int getInteger(String name) {
		return (int) mMap.get(name);
    }


    /**
     * Returns the value of a long key.
     *
     * @throws NullPointerException if the key does not exist or the stored value for the key is
     *         null
     * @throws ClassCastException if the stored value for the key is int, float, ByteBuffer or
     *         String
     */
    /** ARG-V: suitable */
	 public final long getLong(String name) {
		return (long) mMap.get(name);
    }


    /**
     * Returns the value of a float key.
     *
     * @throws NullPointerException if the key does not exist or the stored value for the key is
     *         null
     * @throws ClassCastException if the stored value for the key is int, long, ByteBuffer or
     *         String
     */
    /** ARG-V: suitable */
	 public final float getFloat(String name) {
		return (float) mMap.get(name);
    }

    /**
     * Returns the value of a string key.
     *
     * @return null if the key does not exist or the stored value for the key is null
     * @throws ClassCastException if the stored value for the key is int, long, float or ByteBuffer
     */
    /** ARG-V: suitable */
	 public final String getString(String name) {
		return (String) mMap.get(name);
    }



    /**
     * Returns whether a feature is to be enabled ({@code true}) or disabled
     * ({@code false}).
     *
     * @param feature the name of a {@link MediaCodecInfo.CodecCapabilities} feature.
     *
     * @throws IllegalArgumentException if the feature was neither set to be enabled
     *         nor to be disabled.
     */
    /** ARG-V: suitable */
	 public boolean getFeatureEnabled(String feature) {
        Integer enabled = (Integer)mMap.get(KEY_FEATURE_ + feature);
        if (enabled == null) {
            throw new IllegalArgumentException("feature is not specified");
        }
        assert enabled >= 0; //inline assert generated by ARG-V
		return enabled != 0;
    }

    /**
     * Sets the value of an integer key.
     */
    /** ARG-V: suitable */
	 public final void setInteger(String name, int value) {
        mMap.put(name, value);
    }

    /**
     * Sets the value of a long key.
     */
    /** ARG-V: suitable */
	 public final void setLong(String name, long value) {
        mMap.put(name, value);
    }

    /**
     * Sets the value of a float key.
     */
    /** ARG-V: suitable */
	 public final void setFloat(String name, float value) {
        mMap.put(name, value);
    }

    /**
     * Sets the value of a string key.
     * <p>
     * If value is {@code null}, it sets a null value that behaves similarly to a missing key.
     * This could be used prior to API level {@link android os.Build.VERSION_CODES#Q} to effectively
     * remove a key.
     */
    /** ARG-V: suitable */
	 public final void setString(String name, String value) {
        mMap.put(name, value);
    }


    /**
     * Removes a value of a given key if present. Has no effect if the key is not present.
     */
    /** ARG-V: suitable */
	 public final void removeKey(String name) {
        // exclude feature mappings
        if (!name.startsWith(KEY_FEATURE_)) {
            mMap.remove(name);
        }
    }

    /**
     * Removes a given feature setting if present. Has no effect if the feature setting is not
     * present.
     */
    /** ARG-V: suitable */
	 public final void removeFeature(String name) {
        mMap.remove(KEY_FEATURE_ + name);
    }

    /**
     * Returns a {@link java.util.Set Set} view of the keys contained in this MediaFormat.
     *
     * The set is backed by the MediaFormat object, so changes to the format are reflected in the
     * set, and vice-versa. If the format is modified while an iteration over the set is in progress
     * (except through the iterator's own remove operation), the results of the iteration are
     * undefined. The set supports element removal, which removes the corresponding mapping from the
     * format, via the Iterator.remove, Set.remove, removeAll, retainAll, and clear operations.
     * It does not support the add or addAll operations.
     */
    /** ARG-V: suitable */
	 public final java.util.Set<String> getKeys() {
        assert this.mMap != null; //inline assert generated by ARG-V
		return this.mMap.keySet();
    }


    /**
     * Sets whether a feature is to be enabled ({@code true}) or disabled
     * ({@code false}).
     *
     * If {@code enabled} is {@code true}, the feature is requested to be present.
     * Otherwise, the feature is requested to be not present.
     *
     * @param feature the name of a {@link MediaCodecInfo.CodecCapabilities} feature.
     *
     * @see MediaCodecList#findDecoderForFormat
     * @see MediaCodecList#findEncoderForFormat
     * @see MediaCodecInfo.CodecCapabilities#isFormatSupported
     */
    /** ARG-V: suitable */
	 public void setFeatureEnabled(String feature, boolean enabled) {
        setInteger(KEY_FEATURE_ + feature, enabled ? 1 : 0);
    }


	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main();
		instance.getMap();
        String stringKey = "a" + Verifier.nondetString();
        String stringFeatureKey = KEY_FEATURE_ + stringKey;
        String stringValue = Verifier.nondetString();
        String integerKey = "a" + Verifier.nondetString();
        String integerFeatureKey = KEY_FEATURE_ + integerKey;
        int integerValue = Verifier.nondetInt();
        String longKey = "a" + Verifier.nondetString();
        String longFeatureKey = KEY_FEATURE_ + longKey;
        long longValue = Verifier.nondetLong();
        String floatKey = "a" + Verifier.nondetString();
        String floatFeatureKey = KEY_FEATURE_ + floatKey;
        float floatValue = Verifier.nondetFloat();
        instance.setString(stringKey, stringValue);
        instance.setString(stringFeatureKey, stringValue);
        instance.setInteger(integerKey, integerValue);
        instance.setInteger(integerFeatureKey, integerValue);
        instance.setLong(longKey, longValue);
        instance.setLong(longFeatureKey, longValue);
        instance.setFloat(floatKey, floatValue);
        instance.setFloat(floatFeatureKey, floatValue);

		assert instance.containsKey(stringKey);
        assert instance.containsFeature(stringKey);

		assert instance.getValueTypeForKey(integerKey) == TYPE_INTEGER;

		assert instance.getLong(longKey) == longValue;

        instance.removeKey(floatKey);
		instance.removeFeature(floatFeatureKey);
        assert !instance.containsKey(floatKey);

        boolean enabled = Verifier.nondetBoolean();
        instance.setFeatureEnabled(floatFeatureKey, enabled);
        assert instance.getKeys().contains(floatFeatureKey);
        assert instance.getFeatureEnabled(floatFeatureKey) == enabled;

	}
}
