// SPDX-FileCopyrightText: Copyright (c) 2022-2026 4ra1n (Jar Analyzer Team)
// SPDX-License-Identifier: GPL-3.0-or-later
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * GPLv3 License
 *
 * Copyright (c) 2022-2026 4ra1n (Jar Analyzer Team)
 *
 * This project is distributed under the GPLv3 license.
 *
 * https://github.com/jar-analyzer/jar-analyzer/blob/master/LICENSE
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.util.ArrayList;
import java.util.List;

public class Main {
    private ArrayList<String> interceptors = null;
    private ArrayList<String> servlets = null;
    private ArrayList<String> filters = null;
    private ArrayList<String> listeners = null;

    /** ARG-V: suitable */
	 public Main(
            ArrayList<String> interceptors,
            ArrayList<String> servlets,
            ArrayList<String> filters,
            ArrayList<String> listeners) {
        this.interceptors = interceptors;
        this.servlets = servlets;
        this.filters = filters;
        this.listeners = listeners;
    }

    /** ARG-V: suitable */
	 public void visit(int version, int access, String name, String signature,
                      String superName, String[] interfaces) {
        String currentClassName = name.replace('/', '.');

        if (superName != null) {
            String superClassName = superName.replace('/', '.');
            if (superClassName.equals("javax.servlet.http.HttpServlet") ||
                    superClassName.equals("jakarta.servlet.http.HttpServlet")) {
                servlets.add(currentClassName.replace(".", "/"));
            }

            if (superClassName.equals("org.springframework.web.servlet.handler.HandlerInterceptorAdapter")) {
                interceptors.add(currentClassName.replace(".", "/"));
            }
        }
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        ArrayList<String> interceptors = new ArrayList<String>();
        ArrayList<String> servlets = new ArrayList<String>();
        ArrayList<String> filters = new ArrayList<String>();
        ArrayList<String> listeners = new ArrayList<String>();
        Main instance = new Main(interceptors, servlets, filters, listeners);
        String name = Verifier.nondetString();
        String superName = Verifier.nondetString();
        instance.visit(Verifier.nondetInt(),Verifier.nondetInt(),name,Verifier.nondetString(),superName,new java.lang.String[]{Verifier.nondetString()});
        assert servlets.isEmpty() || (superName.equals("javax/servlet/http/HttpServlet") || superName.equals("jakarta/servlet/http/HttpServlet"));
        assert interceptors.isEmpty() || superName.equals("org/springframework/web/servlet/handler/HandlerInterceptorAdapter");
    }
}
