// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.awt.Rectangle;
import java.util.List;

/**
 * 矩形框文本提取过滤器
 *
 * @author minghu.zhang
 * @since 2021-08-09 20:53:09
 */
public class Main {

    /**
     * 文本提取矩形框
     */
    private Rectangle rectangle = null;

    /** ARG-V: suitable */
	 public Main(Rectangle rectangle) {
        this.rectangle = rectangle;
    }

    /**
     * 空delta值处理
     */
    /** ARG-V: suitable */
	 public void emptyDeltaHandle(String content, List<Float> deltaX, List<Float> deltaY) {
        if (deltaX.isEmpty()) {
            for (int i = 0; i < content.length(); i++) {
                deltaX.add(0F);
            }
        }

        if (deltaY.isEmpty()) {
            for (int i = 0; i < content.length(); i++) {
                deltaY.add(0F);
            }
        }

        assert deltaX.equals(deltaY);
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        Rectangle rectangle = new Rectangle(Verifier.nondetInt(), Verifier.nondetInt(), Verifier.nondetInt(), Verifier.nondetInt());
        List<Float> deltaX = new java.util.ArrayList<Float>();
        List<Float> deltaY = new java.util.ArrayList<Float>();
        // deltaX.add((float)rectangle.getCenterX());
        // deltaY.add((float)rectangle.getCenterY());
        Main instance=new Main(rectangle);
        instance.emptyDeltaHandle(Verifier.nondetString(), deltaX, deltaY);
    }
}
