// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.ByteArrayOutputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.nio.charset.Charset;
import java.util.HashMap;
import java.util.Map;

public class Main {
    // Prefixes for simple primitives. These match the JNI definitions.
    private static byte SIG_BOOLEAN = 'Z';
    private static byte SIG_SHORT = 'S';
    private static byte SIG_INT = 'I';
    private static byte SIG_FLOAT = 'F';

    // Prefixes for some commonly used objects
    private static byte SIG_STRING = 'R';

    private static byte SIG_MAP = 'M'; // a map with an short key
    private static short SIG_END_MAP = 0;

    public DataOutputStream mStream = null;

    private Map<String,Short> mPropertyNames = new HashMap<String, Short>(200);
    private short mPropertyId = 1;
    private Charset mCharset = Charset.forName("utf-8");

    private boolean mUserPropertiesEnabled = true;

    /** ARG-V: suitable */
	 public Main(ByteArrayOutputStream stream) {
        mStream = new DataOutputStream(stream);
    }

    /** ARG-V: suitable */
	 public void setUserPropertiesEnabled(boolean enabled) {
        mUserPropertiesEnabled = enabled;
    }


    /** ARG-V: suitable */
	 public void endObject() {
        endPropertyMap();
    }

    /** ARG-V: suitable */
	 public void endStream() {
        // write out the string table
        startPropertyMap();
        addProperty("__name__", "propertyIndex");
        endPropertyMap();
    }

    /** ARG-V: suitable */
	 public void addProperty(String name, boolean v) {
        writeShort(createPropertyIndex(name));
        writeBoolean(v);
    }

    /** ARG-V: suitable */
	 public void addProperty(String name, short s) {
        writeShort(createPropertyIndex(name));
        writeShort(s);
    }

    /** ARG-V: suitable */
	 public void addProperty(String name, int v) {
        writeShort(createPropertyIndex(name));
        writeInt(v);
    }

    /** ARG-V: suitable */
	 public void addProperty(String name, float v) {
        writeShort(createPropertyIndex(name));
        writeFloat(v);
    }

    /** ARG-V: suitable */
	 public void addProperty(String name, String s) {
        writeShort(createPropertyIndex(name));
        writeString(s);
    }

    /**
     * Encodes a user defined property if they are allowed to be encoded
     *
     * @see #setUserPropertiesEnabled(boolean)
     */
    /** ARG-V: suitable */
	 public void addUserProperty(String name, String s) {
        if (mUserPropertiesEnabled) {
            addProperty(name, s);
        }
    }

    /**
     * Writes the given name as the property name, and leaves it to the callee
     * to fill in value for this property.
     */
    /** ARG-V: suitable */
	 public void addPropertyKey(String name) {
        writeShort(createPropertyIndex(name));
    }

    /** ARG-V: suitable */
	 private short createPropertyIndex(String name) {
        Short index = mPropertyNames.get(name);
        if (index == null) {
            index = mPropertyId++;
            mPropertyNames.put(name, index);
        }

        assert mPropertyId == 2; //inline assert generated by ARG-V
		return index;
    }

    /** ARG-V: suitable */
	 private void startPropertyMap() {
        try {
            mStream.write(SIG_MAP);
        } catch (Exception e) {
            // does not happen since the stream simply wraps a ByteArrayOutputStream
        }
    }

    /** ARG-V: suitable */
	 private void endPropertyMap() {
        writeShort(SIG_END_MAP);
    }

    /** ARG-V: suitable */
	 private void writeBoolean(boolean v) {
        try {
            mStream.write(SIG_BOOLEAN);
            mStream.write(v ? 1 : 0);
        } catch (Exception e) {
            // does not happen since the stream simply wraps a ByteArrayOutputStream
        }
    }

    /** ARG-V: suitable */
	 private void writeShort(short s) {
        try {
            mStream.write(SIG_SHORT);
            mStream.writeShort(s);
        } catch (Exception e) {
            // does not happen since the stream simply wraps a ByteArrayOutputStream
        }
    }

    /** ARG-V: suitable */
	 private void writeInt(int i) {
        try {
            mStream.write(SIG_INT);
            mStream.writeInt(i);
        } catch (Exception e) {
            // does not happen since the stream simply wraps a ByteArrayOutputStream
        }
    }

    /** ARG-V: suitable */
	 private void writeFloat(float v) {
        try {
            mStream.write(SIG_FLOAT);
            mStream.writeFloat(v);
        } catch (Exception e) {
            // does not happen since the stream simply wraps a ByteArrayOutputStream
        }
    }

    /** ARG-V: suitable */
	 private void writeString(String s) {
        if (s == null || s.length() == 0) {
            assert s.equals("");
            s = "";
        }

        try {
            mStream.write(SIG_STRING);
            byte[] bytes = s.getBytes(mCharset);

            short len = (short)Math.min(bytes.length, Short.MAX_VALUE);
            mStream.writeShort(len);

            mStream.write(bytes, 0, len);
        } catch (Exception e) {
            // does not happen since the stream simply wraps a ByteArrayOutputStream
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main(new ByteArrayOutputStream());
		instance.setUserPropertiesEnabled(Verifier.nondetBoolean());
		instance.endObject();
		instance.endStream();
        String stringProperty = "__string__" + Verifier.nondetString();
        String booleanProperty = "__boolean__" + Verifier.nondetString();
        String shortProperty = "__short__" + Verifier.nondetString();
        String intProperty = "__int__" + Verifier.nondetString();
        String floatProperty = "__float__" + Verifier.nondetString();
        instance.addProperty(stringProperty, Verifier.nondetString());
        instance.addProperty(booleanProperty, Verifier.nondetBoolean());
        instance.addProperty(shortProperty, Verifier.nondetShort());
        instance.addProperty(intProperty, Verifier.nondetInt());
        instance.addProperty(floatProperty, Verifier.nondetFloat());
		instance.addUserProperty(stringProperty, Verifier.nondetString());
		instance.addPropertyKey(Verifier.nondetString());
		instance.createPropertyIndex(Verifier.nondetString());
        assert instance.mStream.size() > 0; // all writes could fail

	}
}
