// SPDX-FileCopyrightText: Copyright (C) 2017 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.File;
import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * A dex load reporter which will notify package manager of any dex file loaded
 * with {@code BaseDexClassLoader}.
 * The goals are:
 *     1) discover secondary dex files so that they can be optimized during the
 *        idle maintenance job.
 *     2) determine whether or not a dex file is used by an app which does not
 *        own it (in order to select the optimal compilation method).
 * @hide
 */
/*package*/ class Main {


    // We must guard the access to the list of data directories because
    // we might have concurrent accesses. Apps might load dex files while
    // new data dirs are registered (due to creation of LoadedApks via
    // create createApplicationContext).
    private Set<String> mDataDirs = null;

    /** ARG-V: suitable */
	 private Main() {
        mDataDirs = new HashSet<>();
    }

    /**
     * Register an application data directory with the reporter.
     * The data directories are used to determine if a dex file is secondary dex or not.
     * Note that this method may be called multiple times for the same app, registering
     * different data directories. This may happen when apps share the same user id
     * ({@code android:sharedUserId}). For example, if app1 and app2 share the same user
     * id, and app1 loads app2 apk, then both data directories will be registered.
     */
    /** ARG-V: suitable */
	 /*package*/ void registerAppDataDir(String packageName, String dataDir) {
        if (dataDir != null) {
            synchronized (mDataDirs) {
                mDataDirs.add(dataDir);
            }
        }
    }

    /** ARG-V: suitable */
	 public void report(Map<String, String> classLoaderContextMap) {
        if (classLoaderContextMap.isEmpty()) {
			return;
        }
        assert classLoaderContextMap == null || !classLoaderContextMap.isEmpty();
    }


    /** ARG-V: suitable */
	 private void registerSecondaryDexForProfiling(Set<String> dexPaths) {
        // Make a copy of the current data directories so that we don't keep the lock
        // while registering for profiling. The registration will perform I/O to
        // check for or create the profile.
        String[] dataDirs = new java.lang.String[] { Verifier.nondetString() };
        synchronized (mDataDirs) {
            dataDirs = mDataDirs.toArray(new String[0]);
            assert dataDirs[0].equals(dexPaths.iterator().next());
        }
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        Main instance=new Main();
        String dataDir = Verifier.nondetString();
        instance.registerAppDataDir(Verifier.nondetString(),dataDir);
        instance.report((java.util.Map<java.lang.String, java.lang.String>)null);
        Set<String> set = new HashSet<>();
        set.add(dataDir);
        instance.registerSecondaryDexForProfiling(set);
    }
}
