// SPDX-FileCopyrightText: Copyright (C) 2015 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2015 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.SortedMap;
import java.util.TreeMap;

/**
 * A fixed size cache for custom printer icons. Old icons get removed with a last recently used
 * policy.
 */
public class Main {

    private static String LOG_TAG = "CustomPrinterIconCache";

    /** Maximum number of icons in the cache */
    private static int MAX_SIZE = 1024;

    /** Directory used to persist state and icons */
    private File mCacheDirectory = null;

    /**
     * Create a new icon cache.
     */
    /** ARG-V: suitable */
	 public Main(File cacheDirectory) {
        mCacheDirectory = new File(cacheDirectory, "icons");
        if (!mCacheDirectory.exists()) {
            // mCacheDirectory.mkdir(); cannot instantiate new directory for SV-COMP
        }
    }

    /**
     * Remove old icons so that only between numFilesToKeep and twice as many icons are left.
     *
     * @param numFilesToKeep the number of icons to keep
     */
    /** ARG-V: suitable */
	 public void removeOldFiles(int numFilesToKeep) {
        File files[] = mCacheDirectory.listFiles();

        // To reduce the number of shrink operations, let the cache grow to twice the max size
        if (files != null) {
            if (files.length > numFilesToKeep * 2) {
                SortedMap<Long, File> sortedFiles = new TreeMap<>();

                while (sortedFiles.size() > numFilesToKeep) {
                    // sortedFiles.remove(sortedFiles.firstKey()); cannot remove files for SV-COMP
                    break;
                }
            }
        }
    }

	/** This main was generated by ARG-V */
	
	public static void main(String[] args) throws Exception {
		Main instance = new Main((java.io.File) null);
		instance.removeOldFiles(Verifier.nondetInt());
	}
}
