// SPDX-FileCopyrightText: Copyright (C) 2017 The Android Open Source Project
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright (C) 2026 The ARG-V Project

/** filtered and transformed by ARG-V */

/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import org.sosy_lab.sv_benchmarks.Verifier;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;


public final class Main {
    private static String TAG = "MediaCas";
    private int mPriorityHint = Verifier.nondetInt();
    private String mTvInputServiceSessionId = Verifier.nondetString();
    private int mClientId = Verifier.nondetInt();
    private int mCasSystemId = Verifier.nondetInt();
    private int mUserId = Verifier.nondetInt();

    /** ARG-V: suitable */
	 private void validateInternalStates() {
        if (Verifier.nondetBoolean()) {
            throw new IllegalStateException();
        }
    }

    /** ARG-V: suitable */
	 private void cleanupAndRethrowIllegalState() {
        throw new IllegalStateException();
    }

    /** ARG-V: suitable */
	 private ArrayList<Byte> toByteArray(byte[] data, int offset, int length) {
        ArrayList<Byte> byteArray = new ArrayList<Byte>(length);
        for (int i = 0; i < length; i++) {
            byteArray.add(Byte.valueOf(data[offset + i]));
        }
        assert byteArray.size() == data.length; //inline assert generated by ARG-V
		return byteArray;
    }


    /** ARG-V: suitable */
	 private byte[] toBytes(ArrayList<Byte> byteArray) {
        byte[] data = new byte[] { Verifier.nondetByte() };
        if (byteArray != null) {
            data = new byte[byteArray.size()];
            for (int i = 0; i < data.length; i++) {
                data[i] = byteArray.get(i);
            }
        }
        assert byteArray.equals(Arrays.asList(data)); //inline assert generated by ARG-V
		return data;
    }


    /** ARG-V: suitable */
	 private void createPlugin(int casSystemId) throws Exception {
        try {
            mCasSystemId = casSystemId;
            mUserId = Verifier.nondetInt();
        } catch(Exception e) {
        } finally {
            if (Verifier.nondetBoolean()) {
                throw new Exception();
            }
        }
    }

    /**
     * Instantiate a CA system of the specified system id.
     *
     * @param casSystemId The system id of the CA system.
     *
     * @throws UnsupportedCasException if the device does not support the
     * specified CA system.
     */
    /** ARG-V: suitable */
	 public Main(int casSystemId) throws Exception {
        createPlugin(casSystemId);
    }

    /**
     * Updates client priority with an arbitrary value along with a nice value.
     *
     * <p>Tuner resource manager (TRM) uses the client priority value to decide whether it is able
     * to reclaim insufficient resources from another client.
     *
     * <p>The nice value represents how much the client intends to give up the resource when an
     * insufficient resource situation happens.
     *
     * @see <a
     *     href="https://source.android.com/docs/devices/tv/tuner-framework#priority-nice-value">
     *     Priority value and nice value</a>
     * @param priority the new priority. Any negative value would cause no-op on priority setting
     *     and the API would only process nice value setting in that case.
     * @param niceValue the nice value.
     * @hide
     */
    /** ARG-V: suitable */
	 public boolean updateResourcePriority(int priority, int niceValue) {
        if (Verifier.nondetBoolean()) {
            mPriorityHint = priority;
			return true;
        }
		return false;
    }

    /** ARG-V: suitable */
	 private long getSessionResourceHandle() throws Exception {
        try{
            validateInternalStates();
        } catch (Exception e) {

        }

        long[] sessionResourceHandle = new long[1];
        sessionResourceHandle[0] = -1;
		return sessionResourceHandle[0];
    }



   /**
     * Initiate a provisioning operation for a CA system.
     *
     * @param provisionString string containing information needed for the
     * provisioning operation, the format of which is scheme and implementation
     * specific.
     *
     * @throws IllegalStateException if the MediaCas instance is not valid.
     * @throws MediaCasException for CAS-specific errors.
     * @throws MediaCasStateException for CAS-specific state exceptions.
     */
    /** ARG-V: suitable */
	 public void provision(String provisionString) throws Exception {
        validateInternalStates();

        try {
            if (Verifier.nondetBoolean()) {
                try {
                    if (provisionString == null) {
                        provisionString = "";
                    }
                } catch (Exception e) {
                }
            }
        } catch (Exception e) {
            cleanupAndRethrowIllegalState();
        }
        mTvInputServiceSessionId = provisionString;
    }

	/** This main was generated by ARG-V */
	 public static void main(String[] args) throws Exception{
        Main instance=new Main(Verifier.nondetInt());
        byte[] data=new byte[]{Verifier.nondetByte()};
        ArrayList<Byte> list=instance.toByteArray(data,0,data.length);
        byte[] newData=instance.toBytes(list);
        assert Arrays.equals(newData, data);
        instance.updateResourcePriority(Verifier.nondetInt(),Verifier.nondetInt());
        long sessionResourceHandle = instance.getSessionResourceHandle();
        instance.provision(Verifier.nondetString());
    }
}
